import Fuse from 'fuse.js';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import ContentCard from '../components/organism/ContentCard';
import List from '../constants/video/data';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  // const [searchText, setSearchText] = useState('');
  const [result, setResult] = useState<Array<Fuse.FuseResult<Content>>>([]);

  const options = {
    // isCaseSensitive: false,
    // includeScore: false,
    // shouldSort: true,
    includeMatches: true,
    // findAllMatches: false,
    // minMatchCharLength: 1,
    // location: 0,
    threshold: 0.3,
    // distance: 100,
    // useExtendedSearch: false,
    // ignoreLocation: false,
    // ignoreFieldNorm: false,
    // fieldNormWeight: 1,
    keys: ['song', 'songHira', 'singer', 'singerHira'],
  };

  const handleChange = (event: { target: HTMLInputElement }) => {
    // setSearchText(event.target.value)
    const pattern = event.target.value;
    const fuse = new Fuse(List, options);

    setResult(fuse.search(pattern));
  };

  // Change the pattern

  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <i className='las la-search'></i>
      <i className='lab la-accessible-icon'></i>

      <main className={styles.main}>
        <div className='text-3xl'>
          <span className='text-orange-600 text-3xl font-bold'>V</span>B Music
        </div>

        <div className='mt-6'>
          <div className='flex justify-center'>
            <div className='flex items-center border-2 rounded-md box-shadow w-9/12 m-0 p-0 h-14'>
              <div className='material-icons text-4xl pl-1 pr-1'>search</div>
              <input className='h-10 w-9/12 border-none outline-none' onChange={handleChange} />
            </div>
          </div>
        </div>

        <div className='mt-4'>
          <div className='flex flex-wrap justify-start'>
            {result.map((elm, i) => (
              <ContentCard content={elm} key={i} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
