const L: Array<Content> = [
  {
    song: 'USA',
    songHira: 'ゆーえすえー',
    singer: 'DA PUMP',
    singerHira: 'でぃーえーぽんぷ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=53',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/GdV2_hSHKfk?t=274',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'EXCITE',
    songHira: 'えきさいと',
    singer: '三浦大知',
    singerHira: 'みうらだいち',
    url: 'https://youtu.be/GdV2_hSHKfk?t=519',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '恋',
    songHira: 'こい',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=726',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '新宝島',
    songHira: 'しんたからじま',
    singer: 'サカナクション',
    singerHira: 'さかなくしょん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=984',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '私以外私じゃないの',
    songHira: 'わたしいがいわたしじゃないの',
    singer: 'ゲスの極み乙女。',
    singerHira: 'げすのきわみおとめ。',
    url: 'https://youtu.be/GdV2_hSHKfk?t=1081',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '雨のち晴レルヤ',
    songHira: 'あめのちはれれるや',
    singer: 'ゆず',
    singerHira: 'ゆず',
    url: 'https://youtu.be/GdV2_hSHKfk?t=1349',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '恋音と雨空',
    songHira: 'こいおととあまぞら',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/GdV2_hSHKfk?t=1634',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '女々しくて',
    songHira: 'めめしくて',
    singer: 'ゴールデンボンバー',
    singerHira: 'ごーるでんぼんばー',
    url: 'https://youtu.be/GdV2_hSHKfk?t=1931',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '家族になろうよ',
    songHira: 'かぞくになろうよ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/GdV2_hSHKfk?t=2185',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'Monster',
    songHira: 'もんすたー',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/GdV2_hSHKfk?t=2558',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'また君に恋してる',
    songHira: 'またきみにこいしてる',
    singer: '坂本冬美',
    singerHira: 'さかもとふゆみ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=2892',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'キセキ',
    songHira: 'きせき',
    singer: 'GReeeeN',
    singerHira: 'ぐりーん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=3106',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/GdV2_hSHKfk?t=3365',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '千の風になって',
    songHira: 'せんのかぜになって',
    singer: '秋川雅史',
    singerHira: 'あきかわまさふみ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=3509',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '粉雪',
    songHira: 'こなゆき',
    singer: 'レミオロメン',
    singerHira: 'れみおろめん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=3717',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'さくら',
    songHira: 'さくら',
    singer: 'ケツメイシ',
    singerHira: 'けつめいし',
    url: 'https://youtu.be/GdV2_hSHKfk?t=3959',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '瞳をとじて',
    songHira: 'ひとみをとじて',
    singer: '平井堅',
    singerHira: 'ひらいけん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=4257',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '世界に一つだけの花',
    songHira: 'せかいにひとつだけのはな',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=4505',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '天体観測',
    songHira: 'てんたいかんそく',
    singer: 'BUMP OF CHICKEN',
    singerHira: 'ばんぷおぶちきん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=4754',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'YATTA!',
    songHira: 'やった!',
    singer: 'はっぱ隊',
    singerHira: 'はっぱたい',
    url: 'https://youtu.be/GdV2_hSHKfk?t=4981',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'TSUNAMI',
    songHira: 'つなみ',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/GdV2_hSHKfk?t=5305',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'First Love',
    songHira: 'ふぁーすとらぶ',
    singer: '宇多田ヒカル',
    singerHira: 'うただひかる',
    url: 'https://youtu.be/GdV2_hSHKfk?t=5524',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'Honey',
    songHira: 'はにー',
    singer: "L'Arc-en-Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/GdV2_hSHKfk?t=5734',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '誘惑',
    songHira: 'ゆうわく',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/GdV2_hSHKfk?t=5828',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/GdV2_hSHKfk?t=6046',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '田園',
    songHira: 'でんえん',
    singer: '玉置浩二',
    singerHira: 'たまきこうじ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=6269',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'ズルい女',
    songHira: 'ずるいおんな',
    singer: 'シャ乱Q',
    singerHira: 'しゃらんきゅう',
    url: 'https://youtu.be/GdV2_hSHKfk?t=6521',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'innocent world',
    songHira: 'いのせんとわーるど',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=6748',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'TRUE LOVE',
    songHira: 'とぅるーらぶ',
    singer: '藤井フミヤ',
    singerHira: 'ふじいふみや',
    url: 'https://youtu.be/GdV2_hSHKfk?t=6936',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '時の扉',
    songHira: 'ときのとびら',
    singer: 'WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/GdV2_hSHKfk?t=7548',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '世界が終るまでは…',
    songHira: 'せかいがおわるまでは…',
    singer: 'WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/GdV2_hSHKfk?t=7710',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'それが大事',
    songHira: 'それがだいじ',
    singer: '大事MANブラザーズバンド',
    singerHira: 'だいじまんぶらざーずばんど',
    url: 'https://youtu.be/GdV2_hSHKfk?t=7908',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: 'ラブ・ストーリーは突然に',
    songHira: 'らぶ・すとーりーはとつぜんに',
    singer: '小田和正',
    singerHira: 'おだかずまさ',
    url: 'https://youtu.be/GdV2_hSHKfk?t=8142',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '格好悪いふられ方',
    songHira: 'かっこうわるいふられかた',
    singer: '大江千里',
    singerHira: 'おおえせんり',
    url: 'https://youtu.be/GdV2_hSHKfk?t=8289',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '愛は勝つ',
    songHira: 'あいはかつ',
    singer: 'KAN',
    singerHira: 'かん',
    url: 'https://youtu.be/GdV2_hSHKfk?t=8474',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '川の流れのように',
    songHira: 'かわのながれのように',
    singer: '美空ひばり',
    singerHira: 'みそらひばり',
    url: 'https://youtu.be/GdV2_hSHKfk?t=8807',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/GdV2_hSHKfk?t=9065',
    thumbnails: 'https://img.youtube.com/vi/GdV2_hSHKfk/maxresdefault.jpg',
    title: 'VBの大晦日平成ベストヒットメドレー三味線ライブ',
    date: '2018/12/31',
  },
];

export default L;
