const L: Array<Content> = [
  {
    song: 'PIECES OF A DREAM',
    songHira: 'ぴーすおぶどりーむ',
    singer: 'CHEMISTRY',
    singerHira: 'けみすとりー ',
    url: 'https://youtu.be/42Kf2qcufzM?t=66',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'サマーヌード',
    songHira: 'さまーぬーど',
    singer: '真心ブラザーズ',
    singerHira: 'まごころぶらざーず',
    url: 'https://youtu.be/42Kf2qcufzM?t=251',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'U.S.A.',
    songHira: 'ゆーえすえー',
    singer: 'DA PUMP',
    singerHira: '',
    url: 'https://youtu.be/42Kf2qcufzM?t=298',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'それがすべてさ',
    songHira: 'それがすべてさ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/42Kf2qcufzM?t=511',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'TOKYO通信 ～Urbs Communication～',
    songHira: 'とうきょうつうしん～ゆーあーるびーえすこみゅにけーしょん～',
    singer: "SOUL'd OUT",
    singerHira: 'そーるどあうと',
    url: 'https://youtu.be/42Kf2qcufzM?t=593',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'JUST LIVE MORE',
    songHira: 'じゃすとらいぶもあ',
    singer: 'RIDER CHIPS',
    singerHira: 'らいだーちっぷす',
    url: 'https://youtu.be/42Kf2qcufzM?t=650',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '猟奇的なキスを私にして',
    songHira: 'りょうきてきなきすをわたしにして',
    singer: 'ゲスの極み乙女',
    singerHira: 'げすのきわみおとめ',
    url: 'https://youtu.be/42Kf2qcufzM?t=690',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'サイレントマジョリティー',
    songHira: 'さいれんとまじょりてぃー',
    singer: '櫻坂46',
    singerHira: 'さくらざか46',
    url: 'https://youtu.be/42Kf2qcufzM?t=898',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '君色思い',
    songHira: 'きみいろおもい',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/42Kf2qcufzM?t=947',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'PIKA★★NCHI DOUBLE',
    songHira: 'ぴかんちだぶる',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/42Kf2qcufzM?t=1195',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'again',
    songHira: 'あげいん',
    singer: 'YUI',
    singerHira: 'ゆい',
    url: 'https://youtu.be/42Kf2qcufzM?t=1459',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '夢の外へ',
    songHira: 'ゆめのそとへ',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/42Kf2qcufzM?t=1605',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '銀河鉄道999',
    songHira: 'ぎんがてつどうすりーないん',
    singer: 'ゴダイゴ',
    singerHira: 'ごだいご',
    url: 'https://youtu.be/42Kf2qcufzM?t=1744',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '赤黄色の金木犀',
    songHira: 'あかきいろのきんもくせい',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/42Kf2qcufzM?t=1887',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '二人のアカボシ',
    songHira: 'ふたりのあかぼし',
    singer: 'キンモクセイ',
    singerHira: 'きんのくせい',
    url: 'https://youtu.be/42Kf2qcufzM?t=2114',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'ミラクル',
    songHira: 'みらくる',
    singer: 'miwa',
    singerHira: 'みわ',
    url: 'https://youtu.be/42Kf2qcufzM?t=2256',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '愛されるより愛したい',
    songHira: 'あいされるよりあいしたい',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/42Kf2qcufzM?t=2310',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '愛してるのに、愛せない',
    songHira: 'あいしてるのに、あいせない',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/42Kf2qcufzM?t=2457',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '夏の日の1993',
    songHira: 'なつのひの1993',
    singer: 'Class',
    singerHira: 'くらす',
    url: 'https://youtu.be/42Kf2qcufzM?t=2613',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '青い珊瑚礁',
    songHira: 'あおいさんごしょう',
    singer: '松田聖子',
    singerHira: 'まつだせいこ',
    url: 'https://youtu.be/42Kf2qcufzM?t=2753',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '君が好きだと叫びたい',
    songHira: 'きみがすきだとさけびたい',
    singer: 'BAAD',
    singerHira: 'ばーど',
    url: 'https://youtu.be/42Kf2qcufzM?t=2863',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'アンバランスなKissをして',
    songHira: 'あんばらんすなきすをして',
    singer: '高橋ひろ',
    singerHira: 'たかはしひろ',
    url: 'https://youtu.be/42Kf2qcufzM?t=3068',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'HANABI',
    songHira: 'はなび',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/42Kf2qcufzM?t=3228',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '夏の決心',
    songHira: 'なつのけっしん',
    singer: ' 大江千里',
    singerHira: 'おおえせんり',
    url: 'https://youtu.be/42Kf2qcufzM?t=3530',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'リライト',
    songHira: 'りらいと',
    singer: '',
    singerHira: '',
    url: 'https://youtu.be/42Kf2qcufzM?t=3732',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'Darling',
    songHira: 'だーりん',
    singer: 'ASIAN KUNG-FU GENERATION',
    singerHira: 'あじあんかんふーじぇねれーしょん',
    url: 'https://youtu.be/42Kf2qcufzM?t=3879',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '夢であるように',
    songHira: 'ゆめであるように',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/42Kf2qcufzM?t=4089',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '詠人',
    songHira: 'うたびと',
    singer: '北島三郎',
    singerHira: 'きたじまさぶろう',
    url: 'https://youtu.be/42Kf2qcufzM?t=4332',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'まつり',
    songHira: 'まつり',
    singer: '北島三郎',
    singerHira: 'きたじまさぶろう',
    url: 'https://youtu.be/42Kf2qcufzM?t=4406',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'CQCQ',
    songHira: 'しーきゅーしーきゅー',
    singer: '神様、僕は気づいてしまった',
    singerHira: 'かみさまぼくはきづいてしまった',
    url: 'https://youtu.be/42Kf2qcufzM?t=4432',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'Choo Choo TRAIN',
    songHira: 'ちゅーちゅーとれいん',
    singer: 'EXILE',
    singerHira: 'えぐざいる',
    url: 'https://youtu.be/42Kf2qcufzM?t=4564',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '夏の終わり',
    songHira: 'なつのおわり',
    singer: '森山直太朗',
    singerHira: 'もりやまなおたろう',
    url: 'https://youtu.be/42Kf2qcufzM?t=4757',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'ドラえもん音頭',
    songHira: 'どらえもんおんど',
    singer: '大山のぶ代',
    singerHira: 'おおやまのぶよ',
    url: 'https://youtu.be/42Kf2qcufzM?t=4806',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'いとしのエリー',
    songHira: 'いとしのえりー',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/42Kf2qcufzM?t=4834',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '仮面舞踏会',
    songHira: 'かめんぶとうかい',
    singer: '少年隊',
    singerHira: 'しょうねんたい',
    url: 'https://youtu.be/42Kf2qcufzM?t=4956',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'あー夏休み',
    songHira: 'あーなつやすみ',
    singer: 'TUBE',
    singerHira: 'ちゅーぶ',
    url: 'https://youtu.be/42Kf2qcufzM?t=4994',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: 'HOT LIMIT',
    songHira: 'ほっとりみっと',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/42Kf2qcufzM?t=5184',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '瞳そらさないで',
    songHira: 'ひとみそらさないで',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/42Kf2qcufzM?t=5295',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: "Driver's High",
    songHira: 'どらいばーずはい',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/42Kf2qcufzM?t=5456',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/42Kf2qcufzM?t=5685',
    thumbnails: 'https://img.youtube.com/vi/42Kf2qcufzM/maxresdefault.jpg',
    title: 'お盆だよ全員集合！バーチャルおばあちゃんの三味線ライブ',
    date: '2020/08/18',
  },
];

export default L;
