const L: Array<Content> = [
  {
    song: '格好悪いふられ方',
    songHira: 'かっこうわるいふられほう',
    singer: '大江千里',
    singerHira: 'おおえせんり',
    url: 'https://youtu.be/La_fBYC47EY?t=1300',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'ヨイトマケの唄',
    songHira: 'よいとまけのうた',
    singer: '美輪明宏',
    singerHira: 'みわあきひろ',
    url: 'https://youtu.be/La_fBYC47EY?t=1660',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'if…',
    songHira: 'いふ',
    singer: 'DA PUMP',
    singerHira: 'だぱんぷ',
    url: 'https://youtu.be/La_fBYC47EY?t=1964',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '1/6の夢旅人',
    singer: '樋口了一',
    singerHira: 'ひぐちりょういち',
    songHira: 'いちがつ/むいかのゆめたびびと',
    url: 'https://youtu.be/La_fBYC47EY?t=2198',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'テキトージャクソン',
    songHira: 'てきとーじゃくそん',
    singer: 'VB',
    singerHira: 'ばーちゃるおばあちゃん',
    url: 'https://youtu.be/La_fBYC47EY?t=2429',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '家族になろうよ',
    songHira: 'かぞくになろうよ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/La_fBYC47EY?t=2646',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '夜空ノムコウ',
    songHira: 'よぞらのむこう',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/La_fBYC47EY?t=2949',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'TSUNAMI',
    songHira: 'サザンオールスターズ',
    singer: 'さざんおーるすたーず',
    singerHira: '',
    url: 'https://youtu.be/La_fBYC47EY?t=3152',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'SURPRISE-DRIVE',
    songHira: 'さぷらいず-どらいぶ',
    singer: 'Mitsuru Matsuoka EARNEST DRIVE',
    singerHira: 'みつるまつおかあーねすとどらいぶ',
    url: 'https://youtu.be/La_fBYC47EY?t=3390',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'HANABI',
    songHira: 'はなび',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/La_fBYC47EY?t=3518',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'winter fall',
    songHira: 'うぃんたーふぉーる',
    singer: "L'Arc~en~Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/La_fBYC47EY?t=3828',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '恋',
    songHira: 'こい',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/La_fBYC47EY?t=4111',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '奏',
    songHira: 'かなで',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/La_fBYC47EY?t=4423',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/La_fBYC47EY?t=4669',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'A・RA・SHI',
    songHira: 'あらし',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/La_fBYC47EY?t=4917',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: 'HOT LIMIT',
    songHira: 'ほっとりみっと',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/La_fBYC47EY?t=5090',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '最愛',
    songHira: 'さいあい',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/La_fBYC47EY?t=5307',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/La_fBYC47EY?t=5621',
    thumbnails: 'https://img.youtube.com/vi/La_fBYC47EY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの三味線放送',
    date: '2020/03/10',
  },
];

export default L;
