const L: Array<Content> = [
  {
    song: 'WOW WAR TONIGHT〜時には起こせよムーブメント〜',
    songHira: 'ときにはおこせよむーぶめんと',
    singer: 'H Jungle with t',
    singerHira: 'えいちじゃんぐるうぃずてぃー',
    url: 'https://youtu.be/KzC5LWaVmaU?t=257',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '恋するフォーチュンクッキー',
    songHira: 'こいするふぉーちゅんくっきー',
    singer: 'AKB48',
    singerHira: 'えーけーびー48',
    url: 'https://youtu.be/KzC5LWaVmaU?t=553',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'AMBITIOUS JAPAN!',
    songHira: 'あんびしゃすじゃぱん!',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/KzC5LWaVmaU?t=817',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'One Night Carnival',
    songHira: 'わんないとかーにばる',
    singer: '氣志團',
    singerHira: 'きしだん',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1056',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1270',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '君は薔薇より美しい',
    songHira: 'きみはばらよりうつくしい',
    singer: '布施明',
    singerHira: 'ふせあきら',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1447',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '前前前世',
    songHira: 'ぜんぜんぜんせ',
    singer: 'RADWIMPS',
    singerHira: 'らっどうぃんぷす',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1597',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'ニホンノミカタ-ネバダカラキマシタ-',
    songHira: 'にほんのみかた-ねばだからきました-',
    singer: '矢島美容室',
    singerHira: 'やじまびようしつ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1752',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'ナンダカンダ',
    songHira: 'なんだかんだ',
    singer: '藤井隆',
    singerHira: 'ふじいたかし',
    url: 'https://youtu.be/KzC5LWaVmaU?t=1983',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'Sign',
    songHira: 'さいん',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/KzC5LWaVmaU?t=2227',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '72',
    songHira: 'ななじゅうに',
    singer: '新しい地図',
    singerHira: 'あたらしいちず',
    url: 'https://youtu.be/KzC5LWaVmaU?t=2397',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '青いイナズマ',
    songHira: 'あおいいなずま',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=2749',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '負けないで',
    songHira: 'まけないで',
    singer: 'ZARD',
    singerHira: 'ざーど',
    url: 'https://youtu.be/KzC5LWaVmaU?t=2903',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '浪漫飛行',
    songHira: 'ろまんひこう',
    singer: '米米CLUB',
    singerHira: 'こめこめくらぶ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3000',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'サイレントマジョリティー',
    songHira: 'さいれんとまじょりてぃー',
    singer: '櫻坂46',
    singerHira: 'さくらざか46',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3117',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '世界はそれを愛と呼ぶんだぜ',
    songHira: 'せかいはそれをあいとよぶんだぜ',
    singer: 'サンボマスター',
    singerHira: 'さんぼますたー',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3290',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '化物',
    songHira: 'ばけもの',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3446',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'HOWEVER',
    songHira: 'はうえばー',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3672',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'Honey',
    songHira: 'はにー',
    singer: "L'Arc-en-Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/KzC5LWaVmaU?t=3863',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '夢であるように',
    songHira: 'ゆめであるように',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4014',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '夏色',
    songHira: 'なついろ',
    singer: 'ゆず',
    singerHira: 'ゆず',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4162',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '甘い恋人',
    songHira: 'あまいこいびと',
    singer: 'カジヒデキ',
    singerHira: 'かじひでき',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4306',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'KISSして',
    songHira: 'きすして',
    singer: 'KOH⁺',
    singerHira: 'こー',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4512',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '田園',
    songHira: 'でんえん',
    singer: '玉置浩二',
    singerHira: 'たまきこうじ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4686',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'HERO',
    songHira: 'ひーろー',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4800',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'シングルベッド',
    songHira: 'しんぐるべっど',
    singer: 'シャ乱Q',
    singerHira: 'しゃらんきゅー',
    url: 'https://youtu.be/KzC5LWaVmaU?t=4970',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'ディスコの神様',
    songHira: 'でぃすこのかみさま',
    singer: 'tofubeats',
    singerHira: 'とーふびーつ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=5063',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: 'がんばりましょう',
    songHira: 'がんばりましょう',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/KzC5LWaVmaU?t=5294',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/KzC5LWaVmaU?t=5365',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/KzC5LWaVmaU?t=5444',
    thumbnails: 'https://img.youtube.com/vi/KzC5LWaVmaU/hqdefault.jpg',
    title: '五月病を吹っ飛ばせ！バーチャルおばあちゃん三味線ライブ',
    date: '2020/06/02',
  },
];

export default L;
