const L: Array<Content> = [
  {
    song: '夜桜お七',
    songHira: 'よざくらおしち',
    singer: '坂本冬美',
    singerHira: 'さかもとふゆみ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=25',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '桜',
    songHira: 'さくら',
    singer: 'コブクロ',
    singerHira: 'こぶくろ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=350',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'さくら',
    songHira: 'さくら',
    singer: '森山直太朗',
    singerHira: 'もりやまなおたろう',
    url: 'https://youtu.be/U3XyFV2k2D0?t=624',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'SAKURAドロップス',
    songHira: 'さくらどろっぷ',
    singer: '宇多田ヒカル',
    singerHira: 'うただひかる',
    url: 'https://youtu.be/U3XyFV2k2D0?t=833',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '君は1000%',
    songHira: 'きみはせんぱーせんと',
    singer: 'カルロストシキ・オメガドライブ',
    singerHira: 'かるろすとしき・おめがどらいぶ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=1048',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'チェリー',
    songHira: 'ちぇりー',
    singer: 'スピッツ',
    singerHira: 'すぴっつ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=1216',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '桜色舞うころ',
    songHira: 'さくらまうころ',
    singer: '中島美嘉',
    singerHira: 'なかじまみか',
    url: 'https://youtu.be/U3XyFV2k2D0?t=1367',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'One more time, One more chance',
    songHira: 'わんもあたいむ,わんもあちゃんす',
    singer: '山崎まさよし',
    singerHira: 'やまざきまさよし',
    url: 'https://youtu.be/U3XyFV2k2D0?t=1538',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '桜の季節',
    songHira: 'さくらのきせつ',
    singer: 'ATSUSHI',
    singerHira: 'あつし',
    url: 'https://youtu.be/U3XyFV2k2D0?t=1756',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'Flower',
    songHira: 'ふらわー',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2002',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'フラワー',
    songHira: 'ふらわー',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2179',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん)',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/U3XyFV2k2D0?t=NaN',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'オレンジ',
    songHira: 'おれんじ',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2321',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '君色思い',
    songHira: 'きみいろおもい',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2450',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '叫び',
    songHira: 'さけび',
    singer: '野猿',
    singerHira: 'やえん',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2543',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'Happiness',
    songHira: 'はぴねす',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/U3XyFV2k2D0?t=2780',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'Tomorrow never knows',
    songHira: 'とぅもろーねばーのうず',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3005',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: 'TRUE LOVE',
    songHira: 'とぅるーらぶ',
    singer: '藤井フミヤ',
    singerHira: 'ふじいふみや',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3226',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '桜坂',
    songHira: 'さくらざか',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3372',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '夢の外へ',
    songHira: 'ゆめのそとへ',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3572',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '歩いて帰ろう',
    songHira: 'あるいてかえろう',
    singer: '斉藤和義',
    singerHira: 'さいとうかずよし',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3669',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/U3XyFV2k2D0?t=3867',
    thumbnails: 'https://img.youtube.com/vi/U3XyFV2k2D0/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの夜桜三味線放送',
    date: '2020/03/25',
  },
];

export default L;
