const L: Array<Content> = [
  {
    song: 'ミッドナイトシャッフル',
    songHira: 'みっどないとしゃっふる',
    singer: '近藤真彦',
    singerHira: 'こんどうまさひこ',
    url: 'https://youtu.be/tBU2rEswHYU?t=47',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'さよならの前に',
    songHira: 'さよならのまえに',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/tBU2rEswHYU?t=339',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/tBU2rEswHYU?t=565',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'スリラー',
    songHira: 'すりらー',
    singer: 'Michael Jackson',
    singerHira: 'まいけるじゃくそん',
    url: 'https://youtu.be/tBU2rEswHYU?t=792',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'EXCITE',
    songHira: 'えきさいと',
    singer: '三浦大知',
    singerHira: 'みうらだいち',
    url: 'https://youtu.be/tBU2rEswHYU?t=894',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'SURPRISE-DRIVE',
    songHira: 'さぷらいず-どらいぶ',
    singer: 'Mitsuru Matsuoka EARNEST DRIVE',
    singerHira: 'みつるまつおかあーねすとどらいぶ',
    url: 'https://youtu.be/tBU2rEswHYU?t=1072',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Climax Jump 中居くん乱入ver',
    songHira: 'くらいまっくすじゃんぷ',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/tBU2rEswHYU?t=1227',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Kissからはじまるミステリー',
    songHira: 'きすからはじまるみすてりー',
    singer: '山下達郎',
    singerHira: 'やましたたつろう',
    url: 'https://youtu.be/tBU2rEswHYU?t=1555',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'RevivalRevival',
    songHira: 'りばいばる',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/tBU2rEswHYU?t=1779',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '君じゃなきゃダメみたい',
    songHira: 'きみじゃなきゃだめみたい',
    singer: '大石昌良',
    singerHira: 'おおいしまさよし',
    url: 'https://youtu.be/tBU2rEswHYU?t=2066',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'ワインレッドの心',
    songHira: 'わいんれっどのこころ',
    singer: '安全地帯',
    singerHira: 'あんぜんちたい',
    url: 'https://youtu.be/tBU2rEswHYU?t=2224',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '大都会',
    songHira: 'だいとかい',
    singer: 'クリスタルキング',
    singerHira: 'くりすたるきんぐ',
    url: 'https://youtu.be/tBU2rEswHYU?t=2368',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'オドループ',
    songHira: 'おどるーぷ',
    singer: 'フレデリック',
    singerHira: 'ふれでりっく',
    url: 'https://youtu.be/tBU2rEswHYU?t=2568',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'キラーボール',
    songHira: 'きらーぼーる',
    singer: 'ゲスの極み乙女',
    singerHira: 'げすのきわみおとめ',
    url: 'https://youtu.be/tBU2rEswHYU?t=2785',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Life is SHOW TIME',
    songHira: 'らいふいずしょーたいむ',
    singer: '鬼龍院翔',
    singerHira: 'きりゅういんしょう',
    url: 'https://youtu.be/tBU2rEswHYU?t=2944',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'JUST LIVE MORE',
    songHira: 'じゃすとらいぶもあ',
    singer: '鎧武乃風',
    singerHira: 'がいむのかぜ',
    url: 'https://youtu.be/tBU2rEswHYU?t=3090',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'progress',
    songHira: 'ぷろぐれす',
    singer: 'スガシカオ',
    singerHira: 'すがしかお',
    url: 'https://youtu.be/tBU2rEswHYU?t=3309',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '地上の星',
    songHira: 'ちじょうのほし',
    singer: '中島みゆき',
    singerHira: 'なかじまみゆき',
    url: 'https://youtu.be/tBU2rEswHYU?t=3450',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '勝手にしやがれ Kinki Kids ver',
    songHira: 'かってにしやがれ',
    singer: '沢田研二',
    singerHira: 'さわだけんじ',
    url: 'https://youtu.be/tBU2rEswHYU?t=3609',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Lemon Kinki Kids ver',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/tBU2rEswHYU?t=3750',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Love Phantom',
    songHira: 'らぶふぁんとむ',
    singer: "b'z",
    singerHira: 'びーず',
    url: 'https://youtu.be/tBU2rEswHYU?t=3882',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'flower',
    songHira: 'ふらわー',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/tBU2rEswHYU?t=4045',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'Stand by U',
    songHira: 'すたんどばいばいゆー',
    singer: '東方神起',
    singerHira: 'とうほうしんき',
    url: 'https://youtu.be/tBU2rEswHYU?t=4299',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'I Want it That Way',
    songHira: 'あいうぉんといっとざっとうえー',
    singer: 'Backstreet Boys',
    singerHira: 'ばっくすとりーとぼーいず',
    url: 'https://youtu.be/tBU2rEswHYU?t=4497',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'ぼくらが旅に出る理由',
    songHira: 'ぼくらがたびにでるりゆう',
    singer: '小沢健二',
    singerHira: 'おざわけんじ',
    url: 'https://youtu.be/tBU2rEswHYU?t=4620',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '恋とマシンガン',
    songHira: 'こいとましんがん',
    singer: 'フリッパーズ・ギター',
    singerHira: 'ふりっぱーずぎたー',
    url: 'https://youtu.be/tBU2rEswHYU?t=4745',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '銀河',
    songHira: 'ぎんが',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/tBU2rEswHYU?t=4782',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '突然',
    songHira: 'とつぜん',
    singer: '織田哲郎',
    singerHira: 'おだてつろう',
    url: 'https://youtu.be/tBU2rEswHYU?t=4958',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '最愛',
    songHira: 'さいあい',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/tBU2rEswHYU?t=5132',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: 'アイデア',
    songHira: 'あいであ',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/tBU2rEswHYU?t=5352',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '今日もどこかでデビルマン',
    songHira: 'きょうもどこかででびるまん',
    singer: '十田敬三',
    singerHira: 'とだけいぞう',
    url: 'https://youtu.be/tBU2rEswHYU?t=5517',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/tBU2rEswHYU?t=5581',
    thumbnails: 'https://img.youtube.com/vi/tBU2rEswHYU/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの小悪魔ハロウィン三味線ライブ',
    date: '2018/10/31',
  },
];

export default L;
