const L: Array<Content> = [
  {
    song: 'クリスマスなんて大嫌い!!なんちゃって',
    songHira: 'くりすますなんてだいきらい!!なんちゃって',
    singer: 'クレイジーケンバンド',
    singerHira: 'くれいじーけんばんど',
    url: 'https://youtu.be/808FE3TSuPA?t=55',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'シンデレラクリスマス',
    songHira: 'しんでれらくりすます',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/808FE3TSuPA?t=240',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'いつかのメリークリスマス',
    songHira: 'いつかのめりーくりすます',
    singer: "B'z",
    singerHira: 'びーず',
    url: 'https://youtu.be/808FE3TSuPA?t=460',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '恋人はサンタクロース',
    songHira: 'こいびとはさんたくろーす',
    singer: '松任谷由実',
    singerHira: 'まつとうやゆみ',
    url: 'https://youtu.be/808FE3TSuPA?t=604',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'クリスマス・イブ',
    songHira: 'くりすます・いぶ',
    singer: '山下達郎',
    singerHira: 'やましたたつろう',
    url: 'https://youtu.be/808FE3TSuPA?t=737',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'メリクリ',
    songHira: 'めりくり',
    singer: 'BoA',
    singerHira: 'ぼあ',
    url: 'https://youtu.be/808FE3TSuPA?t=889',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'All I Want For Christmas Is You',
    songHira: 'おーるあいうぉんとふぉーくりすますいずゆー',
    singer: 'Mariah Carey',
    singerHira: 'まらいあきゃりー',
    url: 'https://youtu.be/808FE3TSuPA?t=1024',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'Last Christmas',
    songHira: 'らすとくりすます',
    singer: 'Wham!',
    singerHira: 'わむ!',
    url: 'https://youtu.be/808FE3TSuPA?t=1120',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'Let It Go',
    songHira: 'れっといっとごー',
    singer: '松たか子',
    singerHira: 'まつたかこ',
    url: 'https://youtu.be/808FE3TSuPA?t=1252',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'どんないいこと',
    songHira: 'どんないいこと',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/808FE3TSuPA?t=1429',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'WISH',
    songHira: 'うぃっしゅ',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/808FE3TSuPA?t=1660',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'チキンライス',
    songHira: 'ちきんらいす',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/808FE3TSuPA?t=1868',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'winter fall',
    songHira: 'うぃんたーふぉーる',
    singer: "L'Arc~en~Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/808FE3TSuPA?t=1922',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'Winter,again',
    songHira: 'うぃんたー,あげいん',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/808FE3TSuPA?t=2120',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'WHITE BREATH',
    songHira: 'ほわいとぶれす',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/808FE3TSuPA?t=2321',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'クリスマスキャロルの頃には',
    songHira: 'くりすますきゃろるのころには',
    singer: '稲垣潤一',
    singerHira: 'いながきじゅんいち',
    url: 'https://youtu.be/808FE3TSuPA?t=2483',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '雪の花',
    songHira: 'ゆきのはな',
    singer: '中島美嘉',
    singerHira: 'なかじまみか',
    url: 'https://youtu.be/808FE3TSuPA?t=2564',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '冬が始まるよ',
    songHira: 'ふゆがはじまるよ',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/808FE3TSuPA?t=2742',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'もう恋なんてしないしかわかんない',
    songHira: 'もうこいなんてしないしかわかんない',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/808FE3TSuPA?t=2767',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'ルビーの指輪',
    songHira: 'るびーのゆびわ',
    singer: '寺尾聰',
    singerHira: 'てらおあきら',
    url: 'https://youtu.be/808FE3TSuPA?t=2958',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '恋の魔力 福山雅治ver',
    songHira: 'こいのまりょく',
    singer: 'KOH+',
    singerHira: 'こー+',
    url: 'https://youtu.be/808FE3TSuPA?t=3088',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'もっと強く抱きしめたなら',
    songHira: 'もっとつよくだきしめたなら',
    singer: 'WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/808FE3TSuPA?t=3272',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '君が好き',
    songHira: 'きみがすき',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/808FE3TSuPA?t=3470',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'お家へ帰ろう',
    songHira: 'おうちへかえろう',
    singer: '山崎まさよし',
    singerHira: 'やまざきまさよし',
    url: 'https://youtu.be/808FE3TSuPA?t=3650',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '冬のリヴィエラ',
    songHira: 'ふゆのりゔぃえら',
    singer: '森進一',
    singerHira: 'もりしんいち',
    url: 'https://youtu.be/808FE3TSuPA?t=3765',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'Revival',
    songHira: 'りばいばる',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/808FE3TSuPA?t=3920',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '1/3の純情な感情',
    songHira: '1/3のじゅんじょうなかんじょう',
    singer: 'SIAM SHADE',
    singerHira: 'しゃむしぇいど',
    url: 'https://youtu.be/808FE3TSuPA?t=4090',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '二人のアカボシ',
    songHira: 'ふたりのあかぼし',
    singer: 'キンモクセイ',
    singerHira: 'きんもくせい',
    url: 'https://youtu.be/808FE3TSuPA?t=4242',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '赤黄色の金木犀',
    songHira: 'あかきいろのきんもくせい',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/808FE3TSuPA?t=4408',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '愛のかたまり 癖つよver',
    songHira: 'あいのかたまり',
    singer: 'KinKi Kids',
    singerHira: 'くせのつよいきんききっず',
    url: 'https://youtu.be/808FE3TSuPA?t=4570',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'AMBITIOUS JAPAN!',
    songHira: 'あんびしゃすじゃぱん!',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/808FE3TSuPA?t=4779',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'First impression',
    songHira: 'ふぁーすといんぷれっしょん',
    singer: '野猿',
    singerHira: 'やえん',
    url: 'https://youtu.be/808FE3TSuPA?t=5029',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: 'Sign',
    songHira: 'さいん',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/808FE3TSuPA?t=5225',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '白い恋人達',
    songHira: 'しろいこいびとたち',
    singer: '桑田佳祐',
    singerHira: 'くわたけいすけ',
    url: 'https://youtu.be/808FE3TSuPA?t=5404',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/808FE3TSuPA?t=5565',
    thumbnails: 'https://img.youtube.com/vi/808FE3TSuPA/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線ライブ',
    date: '2018/12/24',
  },
];

export default L;
