const L: Array<Content> = [
  {
    song: '夏の決心',
    songHira: 'なつのけっしん',
    singer: ' 大江千里',
    singerHira: 'おおえせんり',
    url: 'https://youtu.be/JFFNJvXvEWI?t=480',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '新宝島',
    songHira: 'しんたからじま',
    singer: 'サカナクション',
    singerHira: 'さかなくしょん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=767',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '私以外私じゃないの',
    songHira: 'わたしいがいわたしじゃないの',
    singer: 'ゲスの極み乙女',
    singerHira: 'げすのきわみおとめ',
    url: 'https://youtu.be/JFFNJvXvEWI?t=938',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'EXCITE',
    songHira: 'えきさいと',
    singer: '三浦大知',
    singerHira: 'みうらだいち',
    url: 'https://youtu.be/JFFNJvXvEWI?t=1131',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'Climax Jump',
    songHira: 'くらいまっくすじゃんぷ',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/JFFNJvXvEWI?t=1418',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '女々しくて',
    songHira: 'めめしくて',
    singer: 'ゴールデンボンバー',
    singerHira: 'ごーるでんぼんばー',
    url: 'https://youtu.be/JFFNJvXvEWI?t=1716',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'アゲハ蝶',
    songHira: 'あげはちょう',
    singer: 'ポルノグラフィティ',
    singerHira: 'ぽるのぐらふぃてぃ',
    url: 'https://youtu.be/JFFNJvXvEWI?t=1897',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'シーソーゲーム',
    songHira: 'しーそーげーむ',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=2172',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'ひとりじゃない',
    songHira: 'ひとりじゃない',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=2342',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '世界が終わるまでは...',
    songHira: 'せかいがおわるまでは',
    singer: 'WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/JFFNJvXvEWI?t=2538',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'ロマンス',
    songHira: 'ろまんす',
    singer: 'PENICILLIN',
    singerHira: 'ぺにしりん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=2761',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'TOKYO通信 ～Urbs Communication～',
    songHira: 'とうきょうつうしん～ゆーあーるびーえすこみゅにけーしょん～',
    singer: "SOUL'd OUT",
    singerHira: 'そーるどあうと',
    url: 'https://youtu.be/JFFNJvXvEWI?t=2963',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'Love so sweet',
    songHira: 'らぶそすいーと',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/JFFNJvXvEWI?t=3182',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'ジェットコースター・ロマンス',
    songHira: 'じぇっとこーすたー・ろまんす',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/JFFNJvXvEWI?t=3329',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'ウィーアー！',
    songHira: 'うぃーあー！',
    singer: 'きただにひろし',
    singerHira: 'きただにひろし',
    url: 'https://youtu.be/JFFNJvXvEWI?t=3603',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '葛飾ラプソディー',
    songHira: 'かつしからぷそでぃー',
    singer: '堂島孝平',
    singerHira: 'どうじまこうへい',
    url: 'https://youtu.be/JFFNJvXvEWI?t=3807',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '1/3の純情な感情',
    songHira: 'いちがつ/みっかのじゅんじょうなかんじょう',
    singer: 'SIAM SHADE',
    singerHira: 'しゃむしぇいど',
    url: 'https://youtu.be/JFFNJvXvEWI?t=3918',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '世界に一つだけの花',
    songHira: 'せかいにひとつだけのはな',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/JFFNJvXvEWI?t=4114',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '全力少年',
    songHira: 'ぜんりょくしょうねん',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/JFFNJvXvEWI?t=4399',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '虹',
    songHira: 'にじ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/JFFNJvXvEWI?t=4560',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '天体観測',
    songHira: 'てんたいかんそく',
    singer: 'BUMP OF CHICKEN',
    singerHira: 'ばんぷおぶちきん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=4753',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'イノセントワールド',
    songHira: 'いのせんとわーるど',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=4938',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: 'SUN',
    songHira: 'さん',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/JFFNJvXvEWI?t=5177',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか[',
    url: 'https://youtu.be/JFFNJvXvEWI?t=5392',
    thumbnails: 'https://img.youtube.com/vi/JFFNJvXvEWI/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのヤング三味線ライブ',
    date: '2020/03/17',
  },
];

export default L;
