const L: Array<Content> = [
  {
    song: 'さよならの前に',
    songHira: 'さよならのまえに',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/whhg7i0L4qY?t=37',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'AMBITIOUS JAPAN！',
    songHira: 'あんびしゃすじゃぱん！',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/whhg7i0L4qY?t=284',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'リアルフェイス',
    songHira: 'りあるふぇいす',
    singer: 'KAT-TUN',
    singerHira: 'かとぅーん',
    url: 'https://youtu.be/whhg7i0L4qY?t=465',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '逆さまの空',
    songHira: 'さかさまのそら',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/whhg7i0L4qY?t=735',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'LOVEマシーン',
    songHira: 'らぶましーん',
    singer: 'モーニング娘。',
    singerHira: 'もーにんぐむすめ。',
    url: 'https://youtu.be/whhg7i0L4qY?t=891',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King&Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/whhg7i0L4qY?t=1094',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'Share The World',
    songHira: 'しぇあざわーるど',
    singer: '東方神起',
    singerHira: 'とうほうしんき',
    url: 'https://youtu.be/whhg7i0L4qY?t=1313',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'LOVE涙色',
    songHira: 'らぶなみだいろ',
    singer: '松浦亜弥',
    singerHira: 'まつうらあや',
    url: 'https://youtu.be/whhg7i0L4qY?t=1452',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'ガラスの少年',
    songHira: 'がらすのしょうねん',
    singer: 'Kinki Kids',
    singerHira: 'きんききっどず',
    url: 'https://youtu.be/whhg7i0L4qY?t=1542',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: ' 走れ！ ',
    songHira: 'はしれ！',
    singer: 'ももいろクローバーZ',
    singerHira: 'ももいろくろーばーぜっと',
    url: 'https://youtu.be/whhg7i0L4qY?t=1690',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '夢物語',
    songHira: 'ゆめものがたり',
    singer: 'タッキー&翼',
    singerHira: 'たっきーあんどつばさ',
    url: 'https://youtu.be/whhg7i0L4qY?t=1913',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'ジャポニカスタイル',
    songHira: 'じゃぽにかすたいる',
    singer: 'SixTONES',
    singerHira: 'しっくすとーん',
    url: 'https://youtu.be/whhg7i0L4qY?t=2077',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '勇気100%',
    songHira: 'ゆうきひゃくぱーせんと',
    singer: '光GENJI',
    singerHira: 'ひかるげんじ',
    url: 'https://youtu.be/whhg7i0L4qY?t=2268',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'if…',
    songHira: 'いふ',
    singer: 'DA PUMP',
    singerHira: 'だぱんぷ',
    url: 'https://youtu.be/whhg7i0L4qY?t=2427',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'Forever Memories',
    songHira: 'ふぉーえばーえめもりーず',
    singer: 'w-inds.',
    singerHira: 'うぃんず',
    url: 'https://youtu.be/whhg7i0L4qY?t=2578',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '抱いてセニョリータ',
    songHira: 'だいてせにょりーた',
    singer: '山下智久',
    singerHira: 'やましたともひさ',
    url: 'https://youtu.be/whhg7i0L4qY?t=2748',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '恋音と雨空',
    songHira: 'こいおととあまぞら',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/whhg7i0L4qY?t=2878',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '仮面舞踏会',
    songHira: 'かめんぶとうかい',
    singer: '少年隊',
    singerHira: 'しょうねんたい',
    url: 'https://youtu.be/whhg7i0L4qY?t=3094',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '2億4千万の瞳',
    songHira: 'におくよんせんまんのひとみ',
    singer: '郷ひろみ',
    singerHira: 'ごうひろみ',
    url: 'https://youtu.be/whhg7i0L4qY?t=3248',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '時代',
    songHira: 'じだい',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/whhg7i0L4qY?t=3502',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'ひとりじゃない アカペラver',
    songHira: 'ひとりじゃない',
    singer: '堂本剛',
    singerHira: 'どうもとつよし',
    url: 'https://youtu.be/whhg7i0L4qY?t=3652',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'ギザギザハートの子守唄',
    songHira: 'ぎざぎざはーとのこもりうた',
    singer: 'チェッカーズ',
    singerHira: 'ちぇっかーず',
    url: 'https://youtu.be/whhg7i0L4qY?t=3796',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '宇船',
    songHira: 'そらふね',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/whhg7i0L4qY?t=3904',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '天国のキッス',
    songHira: 'てんごくのきっす',
    singer: '松田聖子',
    singerHira: 'まつだせいこ',
    url: 'https://youtu.be/whhg7i0L4qY?t=4095',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'DESIRE',
    songHira: 'でざいあー',
    singer: '中森明菜',
    singerHira: 'なかもりあきな',
    url: 'https://youtu.be/whhg7i0L4qY?t=4225',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'LOSER',
    songHira: 'るーざー',
    singer: '米津玄師',
    singerHira: 'こめつげんし',
    url: 'https://youtu.be/whhg7i0L4qY?t=4434',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'Flamingo',
    songHira: 'ふらみんご',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/whhg7i0L4qY?t=4650',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'message',
    songHira: 'めっせーじ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/whhg7i0L4qY?t=4791',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'Shangri-La',
    songHira: 'しゃんぐりら',
    singer: '電気グルーヴ',
    singerHira: 'でんきぐるーゔ',
    url: 'https://youtu.be/whhg7i0L4qY?t=4811',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '青春アミーゴ',
    songHira: 'せいしゅんあみーご',
    singer: '修二と彰',
    singerHira: 'しゅうじとあきら',
    url: 'https://youtu.be/whhg7i0L4qY?t=4833',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'バラ色の人生',
    songHira: 'ばらいろのじんせい',
    singer: '及川光博',
    singerHira: 'おいかわみつひろ',
    url: 'https://youtu.be/whhg7i0L4qY?t=5021',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King&Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/whhg7i0L4qY?t=5134',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: 'waになって踊ろう',
    songHira: 'わになっておどろう',
    singer: 'V6',
    singerHira: 'ぶいしっくす',
    url: 'https://youtu.be/whhg7i0L4qY?t=5485',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/whhg7i0L4qY?t=5583',
    thumbnails: 'https://img.youtube.com/vi/whhg7i0L4qY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのキラキラ☆逮捕アイドル三味線ライブ【AAA】',
    date: '2019/04/20',
  },
];

export default L;
