const L: Array<Content> = [
  {
    song: "Burnin 'X'mas",
    songHira: 'ばーにんくりすます',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=53',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'クリスマスキャロルの頃には',
    songHira: 'くりすますきゃろるのころには',
    singer: '稲垣潤一',
    singerHira: 'いながきじゅんいち',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=322',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'クリスマスソング',
    songHira: 'くりすますそんぐ',
    singer: 'back number',
    singerHira: 'ばっくなんばー',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=566',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'チキンライス',
    songHira: 'ちきんらいす',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=799',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '空の青さを知る人よ',
    songHira: 'そらのあおさをしるひとよ',
    singer: 'あいみょん',
    singerHira: 'あいみょん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=883',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '粉雪',
    songHira: 'こなゆき',
    singer: 'レミオロメン',
    singerHira: 'れみおろめん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=1077',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'いつかのメリークリスマス',
    songHira: 'いつかのめりーくりすます',
    singer: "B'z",
    singerHira: 'びーず',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=1274',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'orion',
    songHira: 'おりおん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=1490',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'まちがいさがし',
    songHira: 'まちがいさがし',
    singer: '菅田将暉',
    singerHira: 'すだまさき',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=1681',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'snow drop',
    songHira: 'すのー どろっぷ',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=1856',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '若者のすべて',
    songHira: 'わかもののすべて',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=2036',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '冬の磁石',
    songHira: 'ふゆのじしゃく',
    singer: 'キンモクセイ',
    singerHira: 'きんもくせい',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=2242',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'ハチミツ',
    songHira: 'はちみつ',
    singer: 'スピッツ',
    singerHira: 'すぴっつ',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=2496',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=2677',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'イエスタデイ',
    songHira: 'いえすたでい',
    singer: 'Offcial髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=2925',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '丸の内サディスティック',
    songHira: 'まるのうち さでぃすてぃっく',
    singer: '椎名林檎',
    singerHira: 'しいなりんご',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3178',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '灰色と青',
    songHira: 'はいいろとあお',
    singer: '菅田将暉',
    singerHira: 'すだまさき',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3326',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'クリスマスイブ',
    songHira: 'くりすますいぶ',
    singer: '山下達郎',
    singerHira: 'やましたたつろう',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3541',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '白い恋人達',
    songHira: 'しろいこいびとたち',
    singer: '桑田佳祐',
    singerHira: 'くわたけいすけ',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3637',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'メリクリ',
    songHira: 'めりくり',
    singer: 'BoA',
    singerHira: 'ぼあ',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3809',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '愛されるよりも愛したい',
    songHira: 'あいされるよりもあいしたい',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=3999',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'Smooth criminal',
    songHira: 'すむーずくりみなる',
    singer: 'Michael Jackson',
    singerHira: 'まいけるじゃくそん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4169',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'このまま君だけを奪い去りたい',
    songHira: 'このままきみだけをうば さりたい',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4275',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'ひとりじゃない',
    songHira: 'ひとりじゃない',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4425',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '奏',
    songHira: 'かなで',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4592',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'WISH',
    songHira: 'うぃっしゅ',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4720',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: 'Winter again',
    songHira: 'うぃんたーあげいん',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=4923',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '地獄でなぜ悪い',
    songHira: 'じごくで なぜ わるい',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=5118',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '家族になろうよ',
    songHira: 'かぞくになろうよ',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=5331',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '願い',
    songHira: 'ねがい',
    singer: 'sumika',
    singerHira: 'すみか',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=5632',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/oT1Bhm2hIj4?t=5731',
    thumbnails: 'https://img.youtube.com/vi/oT1Bhm2hIj4/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマスろまんてっく三味線ライブ',
    date: '2019/12/24',
  },
];

export default L;
