const L: Array<Content> = [
  {
    song: 'ひとりぼっちのハブラシ。',
    songHira: 'ひとりぼっちのはぶらし。',
    singer: '桜庭裕一郎',
    singerHira: 'さくらばゆういちろう',
    url: 'https://youtu.be/UNa5-6hXpwI?t=93',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '愛のかたまり',
    songHira: 'あいのかたまり',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/UNa5-6hXpwI?t=314',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'One Love',
    songHira: 'わんらぶ',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=560',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'SUMMER NUDE’13',
    songHira: 'さまーぬーど13',
    singer: '山下智久',
    singerHira: 'やましたともひさ',
    url: 'https://youtu.be/UNa5-6hXpwI?t=749',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Venus',
    songHira: 'びーなす',
    singer: 'タッキー＆翼',
    singerHira: 'たっきーあんどつばさ',
    url: 'https://youtu.be/UNa5-6hXpwI?t=924',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'JAPONICA STYLE',
    songHira: 'じゃぽにかすたいる',
    singer: 'SixTONES',
    singerHira: 'しっくすとーん',
    url: 'https://youtu.be/UNa5-6hXpwI?t=1062',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Snow Dream',
    songHira: 'すのーどりーむ',
    singer: 'Snow Man',
    singerHira: 'すのーまん',
    url: 'https://youtu.be/UNa5-6hXpwI?t=1245',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King & Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/UNa5-6hXpwI?t=1538',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'CHANGE THE WORLD',
    songHira: 'ちぇんじざわーるど',
    singer: 'V6',
    singerHira: 'ぶいしっくす',
    url: 'https://youtu.be/UNa5-6hXpwI?t=1780',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Love so sweet',
    songHira: 'らぶそすいーと',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2026',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '海の幽霊',
    songHira: 'うみのゆうれい',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2215',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '桜坂',
    songHira: 'さくらざか',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2385',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2535',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '72',
    songHira: 'ななじゅうに',
    singer: '新しい地図',
    singerHira: 'あたらしいちず',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2694',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Real Face SHIZUKA ver',
    songHira: 'りあるふぇいす',
    singer: 'KAT-TUN',
    singerHira: 'かとぅーん',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2826',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '宙船',
    songHira: 'そらふね',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/UNa5-6hXpwI?t=2956',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '青春アミーゴ',
    songHira: 'せいしゅんあみーご',
    singer: '修二と彰',
    singerHira: 'しゅうじとあきら',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3132',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'What Do You Mean？',
    songHira: 'ふぁっとどゆーみーん？',
    singer: 'Justin Bieber',
    singerHira: 'じゃすてぃんびーばー',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3255',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '冬のリヴィエラ',
    songHira: 'ふゆのりゔぃえら',
    singer: '森進一',
    singerHira: 'もりしんいち',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3330',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '逢いたくてしかたない',
    songHira: 'あいたくてしかたない',
    singer: '郷ひろみ',
    singerHira: 'ごうひろみ',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3489',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '恋音と雨空',
    songHira: 'こいおととあまぞら',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3632',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'POISON～言いたいことも言えないこんな世の中じゃ～',
    songHira: 'ぽいずん～いいたいこともいえないこんなよのなかじゃー',
    singer: '反町隆史',
    singerHira: 'そりまちたかし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3890',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '少年時代',
    songHira: 'しょうねんじだい',
    singer: '',
    singerHira: '',
    url: 'https://youtu.be/UNa5-6hXpwI?t=3949',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'シンデレラガール hyde ver',
    songHira: 'しんでれらがーる',
    singer: 'King & Prince',
    singerHira: '',
    url: 'https://youtu.be/UNa5-6hXpwI?t=4117',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Flower 中居ver',
    songHira: 'ふらわー',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/UNa5-6hXpwI?t=4314',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '慎吾ママのおはロック',
    songHira: 'しんごままのおはろっく',
    singer: '香取慎吾',
    singerHira: 'かとりしんご',
    url: 'https://youtu.be/UNa5-6hXpwI?t=4502',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '前前前世',
    songHira: 'ぜんぜんぜんせ',
    singer: 'RADWIMPS',
    singerHira: 'らっどうぃんぷす',
    url: 'https://youtu.be/UNa5-6hXpwI?t=4616',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'らいおんハート',
    songHira: 'らいおんはーと',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/UNa5-6hXpwI?t=4765',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Monster',
    songHira: 'もんすたー',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=5070',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Happiness',
    songHira: 'はぴねす',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/UNa5-6hXpwI?t=5227',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: 'Anniversary',
    songHira: 'あにばーさりー',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/UNa5-6hXpwI?t=5485',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/UNa5-6hXpwI?t=5618',
    thumbnails: 'https://img.youtube.com/vi/UNa5-6hXpwI/maxresdefault.jpg',
    title: 'お盆だよ！バーチャルおばあちゃんのありがとうジャニーさん三味線ライブ',
    date: '2019/08/12',
  },
];

export default L;
