const L: Array<Content> = [
  {
    song: '即興ソング墓',
    songHira: 'そっきょうそんぐはか',
    singer: 'VB',
    singerHira: 'ばーちゃるおばあちゃん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=495',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/Oo6JTALObXQ?t=645',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'winter fall',
    songHira: 'うぃんたーふぉーる',
    singer: 'L’Arc〜en〜Ciel',
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/Oo6JTALObXQ?t=884',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '世界が終わるまでは...',
    songHira: 'せかいがおわるまでは',
    singer: 'WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/Oo6JTALObXQ?t=1137',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'HANABI',
    songHira: 'えっちえーえぬえーびーあい',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=1375',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '真夏の果実',
    songHira: 'まなつのかじつ',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/Oo6JTALObXQ?t=1603',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '化物',
    songHira: 'ばけもの',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=1851',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '夢であるように',
    songHira: 'ゆめであるように',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=2120',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '夏の日の1993',
    songHira: 'なつのひの1993',
    singer: 'class',
    singerHira: 'くらす',
    url: 'https://youtu.be/Oo6JTALObXQ?t=2304',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Happiness',
    songHira: 'はぴねす',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/Oo6JTALObXQ?t=2526',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King&Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/Oo6JTALObXQ?t=2760',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '1/3の純情な感情',
    songHira: '1/3のじゅんじょうなかんじょう',
    singer: 'SIAM SHADE',
    singerHira: 'しゃむしぇいど',
    url: 'https://youtu.be/Oo6JTALObXQ?t=2973',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '赤黄色の金木犀',
    songHira: 'あかきいろのきんもくせい',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/Oo6JTALObXQ?t=3106',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '高嶺の花子さん',
    songHira: 'たかねのはなこさん',
    singer: 'back number',
    singerHira: 'ばっくなんばー',
    url: 'https://youtu.be/Oo6JTALObXQ?t=3387',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Squall',
    songHira: 'すこーる',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/Oo6JTALObXQ?t=3501',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'ワインレッドの心',
    songHira: 'わいんれっどのこころ',
    singer: '安全地帯',
    singerHira: 'あんぜんちたい',
    url: 'https://youtu.be/Oo6JTALObXQ?t=3677',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'HOT LIMIT',
    songHira: 'ほっとりみっと',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=3850',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Lemon',
    songHira: 'れもん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4012',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '誘惑',
    songHira: 'ゆうわく',
    singer: 'GRAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4162',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '千の風になって',
    songHira: 'せんのかぜになって',
    singer: '秋川雅史',
    singerHira: 'あきかわまさふみ',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4318',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'もののけ姫',
    songHira: 'もののけひめ',
    singer: '米良美一',
    singerHira: 'めらよしかず',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4376',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '猟奇的なキスを私にして',
    songHira: 'りょうきてきなきすをわたしにして',
    singer: 'ゲスの極み乙女',
    singerHira: 'げすのきわみおとめ',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4465',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'if…',
    songHira: 'いふ',
    singer: 'DA PUMP',
    singerHira: 'だぱんぷ',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4616',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '新宝島',
    songHira: 'しんたからじま',
    singer: 'サカナクション',
    singerHira: 'さかなくしょん',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4782',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '奏',
    songHira: 'かなで',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/Oo6JTALObXQ?t=4892',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'One more time,One more chance',
    songHira: 'わんもあたいむ,わんもあちゃんす',
    singer: '山崎まさよし',
    singerHira: 'やまざきまさよし',
    url: 'https://youtu.be/Oo6JTALObXQ?t=5109',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '二人のアカボシ',
    songHira: 'ふたりのあかぼし',
    singer: 'キンモクセイ',
    singerHira: 'きんもくせい',
    url: 'https://youtu.be/Oo6JTALObXQ?t=5291',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Driver’s High',
    songHira: 'どらいばーずはい',
    singer: 'L’Arc〜en〜Ciel',
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/Oo6JTALObXQ?t=5524',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/Oo6JTALObXQ?t=5751',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
];

export default L;
