const L: Array<Content> = [
  {
    song: '君は1000%',
    songHira: 'きみはせんぱーせんと',
    singer: 'カルロストシキ・オメガドライブ',
    singerHira: 'かるろすとしき・おめがどらいぶ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=71',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'フライディ・チャイナタウン',
    songHira: 'ふらいでぃ・ちゃいなたうん',
    singer: '泰葉',
    singerHira: 'やすは',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=275',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'マリーゴーロルド',
    songHira: 'まりーごーろるど',
    singer: 'ばばみょん',
    singerHira: 'ばばみょん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=439',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '馬と鹿',
    songHira: 'うまとしか',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=721',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '忘れられないの',
    songHira: 'わすれられないの',
    singer: 'サカナクション',
    singerHira: 'さかなくしょん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=950',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=1243',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '若者のすべて',
    songHira: 'わかもののすべて',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=1445',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'また君に恋してる',
    songHira: 'またきみにこいしてる',
    singer: '坂本冬美',
    singerHira: 'さかもとふゆみ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=1546',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'リブート',
    songHira: 'りぶーと',
    singer: 'miwa',
    singerHira: 'みわ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=1716',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Pretender',
    songHira: 'ぷれてんだー',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=1924',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'もう恋なんてしない',
    songHira: 'もうこいなんてしない',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2130',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '夏の終わり',
    songHira: 'なつのおわり',
    singer: '森山直太朗',
    singerHira: 'もりやまなおたろう',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2301',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'きっと大丈夫',
    songHira: 'きっとだいじょうぶ',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2458',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '虹',
    songHira: 'にじ',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2672',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '灰色と青',
    songHira: 'はいいろとあお',
    singer: '菅田将暉',
    singerHira: 'すだまさき',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2798',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '海の声',
    songHira: 'うみのこえ',
    singer: '桐谷健太',
    singerHira: 'きりがやけんた',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2946',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '甘い恋人',
    songHira: 'あまいこいびと',
    singer: '根岸崇一',
    singerHira: 'ねぎしそういち',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=2982',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'ハミングがきこえる',
    songHira: 'はみんぐがきこえる',
    singer: 'カヒミカリィ',
    singerHira: 'かひみかりぃ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3121',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'ようこそジャパリパークへ',
    songHira: 'ようこそじゃぱりぱーくへ',
    singer: '大石昌良',
    singerHira: 'おおいしまさよし',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3236',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '全力少年',
    songHira: 'ぜんりょくしょうねん',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3401',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'シーソーゲーム',
    songHira: 'しーそーげーむ',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3596',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'カルマ',
    songHira: 'かるま',
    singer: 'BUMP OF CHICKEN',
    singerHira: 'ばんぷおぶちきん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3780',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '高嶺の花子さん',
    songHira: 'たかねのはなこさん',
    singer: 'back number ',
    singerHira: 'ばっくなんばー',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=3945',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'まぼろしの人',
    songHira: 'まぼろしのひと',
    singer: '茶木みやこ',
    singerHira: 'ちゃきみやこ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4128',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'オドループ',
    songHira: 'おどるーぷ',
    singer: 'フレデリック',
    singerHira: 'ふれでりっく',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4339',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'CQCQ',
    songHira: 'しーきゅーしーきゅー',
    singer: '神様、僕は気づいてしまった',
    singerHira: 'かみさま、ぼくはきづいてしまった',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4443',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'ムーンライト',
    songHira: 'むーんらいと',
    singer: 'くず',
    singerHira: 'くず',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4576',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'エイリアンズ',
    songHira: 'えいりあんず',
    singer: 'キリンジ',
    singerHira: 'きりんじ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4665',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4741',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'Glass',
    songHira: 'ぐらす',
    singer: '河村隆一',
    singerHira: 'かわむらりゅういち',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4861',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'キラーチューン',
    songHira: 'きらーちゅーん',
    singer: '東京事変',
    singerHira: 'とうきょうじへん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=4916',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '葛飾ラプソディー',
    songHira: 'かつしからぷそでぃー',
    singer: '堂島孝平',
    singerHira: 'どうじまこうへい',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=5091',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '喝采',
    songHira: 'かっさい',
    singer: 'ちあきなおみ',
    singerHira: 'ちあきなおみ',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=5212',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'パプリカ',
    songHira: 'ぱぷりか',
    singer: '米津玄師',
    singerHira: 'こめつげんし',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=5348',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: 'アイデア',
    songHira: 'あいであ',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=5521',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/AQYrlYvI9Wo?t=5694',
    thumbnails: 'https://img.youtube.com/vi/AQYrlYvI9Wo/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんの敬老の日三味線ライブ',
    date: '2019/09/16',
  },
];

export default L;
