const L: Array<Content> = [
  {
    song: 'もう恋なんてしない',
    songHira: 'もうこいなんてしない',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/tSUUn1e2NY4?t=56',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Teenager Forever',
    songHira: 'てぃーんねいじゃーふぉーえばー',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/tSUUn1e2NY4?t=524',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'CHA-RA-HEAD-CHA-RA',
    songHira: 'ちゃらへっちゃら',
    singer: '影山ヒロノブ',
    singerHira: 'かげやまひろのぶ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=753',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Pretender',
    songHira: 'ぷれてんだー',
    singer: 'official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=921',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'カナシミブルー',
    songHira: 'かなしみぶるー',
    singer: 'Kinki Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/tSUUn1e2NY4?t=1179',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'ピースサイン',
    songHira: 'ぴーすさいん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/tSUUn1e2NY4?t=1436',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'チョコレイトディスコ',
    songHira: 'ちょこれいとでぃすこ',
    singer: 'perfume',
    singerHira: 'ぱふぃーむ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=1635',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '冬がはじまるよ',
    songHira: 'ふゆがはじまるよ',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/tSUUn1e2NY4?t=1824',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Shangri-La',
    songHira: 'しゃんぐりら',
    singer: '電気グルーヴ',
    singerHira: 'でんきぐるーゔ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=2026',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '恋音と雨空',
    songHira: 'こいおんとあまぞら',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/tSUUn1e2NY4?t=2175',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'SAY YES',
    songHira: 'せいいえす',
    singer: 'CHAGE and ASKA',
    singerHira: 'ちゃげあんどあすか',
    url: 'https://youtu.be/tSUUn1e2NY4?t=2422',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'AMBITIOUS JAPAN',
    songHira: 'あんびしゃすじゃぱん',
    singer: 'TOKIO',
    singerHira: 'ときお',
    url: 'https://youtu.be/tSUUn1e2NY4?t=2644',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Snow dream',
    songHira: 'すのーどりーむ',
    singer: 'snow man',
    singerHira: 'すのーまん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=2846',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'JAPONICA STYLE',
    songHira: 'じゃぽにかすたいる',
    singer: 'SixTONES',
    singerHira: 'しっくすとーん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=3046',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Youthful days',
    songHira: 'ゆーすふるでいず',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=3257',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Sign',
    songHira: 'さいん',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=3452',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'どんなときも',
    songHira: 'どんなときも',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/tSUUn1e2NY4?t=3656',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'POP STAR',
    songHira: 'ぽっぷすたー',
    singer: '平井堅',
    singerHira: 'ひらいけん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=3903',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'ひとりじゃない',
    songHira: 'ひとりじゃない',
    singer: 'DEEN',
    singerHira: 'でぃーん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4092',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'HONEY',
    songHira: 'はにー',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4289',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'リブート',
    songHira: 'りぶーと',
    singer: 'miwa',
    singerHira: 'みわ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4399',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '雨のち晴レルヤ',
    songHira: 'あめのちはれれるや',
    singer: 'ゆず',
    singerHira: 'ゆず',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4555',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'イエスタデイ',
    songHira: 'いえすたでい',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4748',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Yesterday',
    songHira: 'いえすたでー',
    singer: 'BEATLES',
    singerHira: 'びーとるず',
    url: 'https://youtu.be/tSUUn1e2NY4?t=4865',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '願い',
    songHira: 'ねがい',
    singer: 'sumika',
    singerHira: 'すみか',
    url: 'https://youtu.be/tSUUn1e2NY4?t=5015',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Revival',
    songHira: 'りばいばる',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/tSUUn1e2NY4?t=5218',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'いとしのエリー',
    songHira: 'いとしのえりー',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/tSUUn1e2NY4?t=5395',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'SUN',
    songHira: 'さん',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=5617',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Real face',
    songHira: 'りあるふぇいす',
    singer: 'KAT-TUN',
    singerHira: 'かとぅーん',
    url: 'https://youtu.be/tSUUn1e2NY4?t=5834',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: 'Love so sweet',
    songHira: 'らぶそーすいーと',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/tSUUn1e2NY4?t=6050',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '世界に一つだけの花',
    songHira: 'せかいにひとつだけのはな',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/tSUUn1e2NY4?t=6226',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/tSUUn1e2NY4?t=6548',
    thumbnails: 'https://img.youtube.com/vi/tSUUn1e2NY4/maxresdefault.jpg',
    title: 'VBのもうチョコなんていらないなんて言わないで絶対バレンタイン三味線ライブ',
    date: '2020/02/14',
  },
];

export default L;
