const L: Array<Content> = [
  {
    song: '北ウイング',
    songHira: 'きたういんぐ',
    singer: '中森明菜',
    singerHira: 'なかもりあきな',
    url: 'https://youtu.be/1OY_S4XNpFk?t=28',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '夜に駆ける',
    songHira: 'よるにかける',
    singer: 'YOASOBI',
    singerHira: 'よあそび',
    url: 'https://youtu.be/1OY_S4XNpFk?t=309',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '木綿のハンカチーフ',
    songHira: 'もめんのはんかちーふ',
    singer: '太田裕美',
    singerHira: 'おおたひろみ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=581',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '猫 THE FIRST TAKE ver',
    songHira: 'ねこ',
    singer: 'DISH//',
    singerHira: 'でぃっしゅ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=743',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'シンデレラ・ハネムーン',
    songHira: 'しんでれら・はねむーん',
    singer: '岩崎宏美',
    singerHira: 'いわさきひろみ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=966',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '炎',
    songHira: 'ほのお',
    singer: 'LiSA',
    singerHira: 'りさ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=1110',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '冬のリヴィエラ',
    songHira: 'ふゆのりゔぃえら',
    singer: '森進一',
    singerHira: 'もりしんいち',
    url: 'https://youtu.be/1OY_S4XNpFk?t=1370',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'カナリヤ',
    songHira: 'かなりや',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/1OY_S4XNpFk?t=1583',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '勝手にしやがれ',
    songHira: 'かってにしやがれ',
    singer: '沢田研二',
    singerHira: 'さわだけんじ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=1782',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '115万キロのフィルム',
    songHira: '115まんきろのふぃるむ',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=2011',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'innocent world',
    songHira: 'いのせんとわーるど',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/1OY_S4XNpFk?t=2241',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '君は薔薇より美しい',
    songHira: 'きみはばらよりうつくしい',
    singer: '布施明',
    singerHira: 'ふせあきら',
    url: 'https://youtu.be/1OY_S4XNpFk?t=2438',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '今夜はブギーバック',
    songHira: 'こんやはぶぎーばっく',
    singer: '小沢健二',
    singerHira: 'おざわけんじ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=2685',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'スマイル',
    songHira: 'すまいる',
    singer: '森菜々',
    singerHira: 'もりなな',
    url: 'https://youtu.be/1OY_S4XNpFk?t=2911',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '葛飾ラプソディー',
    songHira: 'かつしからぷそでぃー',
    singer: '堂島孝平',
    singerHira: 'どうじまこうへい',
    url: 'https://youtu.be/1OY_S4XNpFk?t=3045',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '最愛',
    songHira: 'さいあい',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/1OY_S4XNpFk?t=3173',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'PIECES OF ADREAM',
    songHira: 'ぷりんせすおぶどりーむ',
    singer: 'CHEMISTRY',
    singerHira: 'けみすとりー',
    url: 'https://youtu.be/1OY_S4XNpFk?t=3419',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'まいった',
    songHira: 'まいった',
    singer: 'sumika',
    singerHira: 'すみか',
    url: 'https://youtu.be/1OY_S4XNpFk?t=3651',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'Forever Memories',
    songHira: 'ふぉーえばーめもりーず',
    singer: 'Day of the legend',
    singerHira: 'でいおぶざれじぇんど',
    url: 'https://youtu.be/1OY_S4XNpFk?t=3874',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '丸の内サディスティック',
    songHira: 'まるのうちさでぃすてぃっく',
    singer: '椎名林檎',
    singerHira: 'しいなりんご',
    url: 'https://youtu.be/1OY_S4XNpFk?t=4095',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'カナシミブルー',
    songHira: 'かなしみぶるー',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/1OY_S4XNpFk?t=4235',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'A・RA・SHI',
    songHira: 'あらし',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/1OY_S4XNpFk?t=4544',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'サマーヌード',
    songHira: 'さまーぬーど',
    singer: '真心ブラザーズ',
    singerHira: 'まごころぶらざーず',
    url: 'https://youtu.be/1OY_S4XNpFk?t=4787',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '私のなかの銀河',
    songHira: 'わたしのなかのぎんが',
    singer: '海援隊',
    singerHira: 'かいえんたい',
    url: 'https://youtu.be/1OY_S4XNpFk?t=4922',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'オドループ',
    songHira: 'おどるーぷ',
    singer: 'フレデリック',
    singerHira: 'ふれでりっく',
    url: 'https://youtu.be/1OY_S4XNpFk?t=5058',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'September',
    songHira: 'せぷてんばー',
    singer: 'Earth, Wind & Fire',
    singerHira: 'あーすういんどあんどふぁいあ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=5250',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '手のひらを太陽に',
    songHira: 'てのひらをたいように',
    singer: 'EIKO',
    singerHira: 'えいこ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=5454',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '夕焼け小焼け',
    songHira: 'ゆうやけこやけ',
    singer: 'EIKO',
    singerHira: 'えいこ',
    url: 'https://youtu.be/1OY_S4XNpFk?t=5621',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'SUN',
    songHira: 'さん',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/1OY_S4XNpFk?t=5801',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: 'winterfall',
    songHira: 'うぃんたーふぉーる',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/1OY_S4XNpFk?t=6007',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/1OY_S4XNpFk?t=6237',
    thumbnails: 'https://img.youtube.com/vi/1OY_S4XNpFk/maxresdefault.jpg',
    title: 'バーチャルおばあちゃん愛の三味線ライブ～昭和と令和を繋いで～',
    date: '2020/11/25',
  },
];

export default L;
