const L: Array<Content> = [
  {
    song: 'シンデレラ・クリスマス',
    songHira: 'しんでれら・くりすます',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/HoL1PbSyBI0?t=22',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'クリスマス・イブ',
    songHira: 'くりすます・いぶ',
    singer: '山下達郎',
    singerHira: 'やましたたつろう',
    url: 'https://youtu.be/HoL1PbSyBI0?t=335',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'All I Want for Christmas is You',
    songHira: 'おーるあいうぉんとふぉーくりすますいずゆー',
    singer: 'マライア・キャリー',
    singerHira: 'まらいあきゃりー',
    url: 'https://youtu.be/HoL1PbSyBI0?t=509',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'クリスマスソング',
    songHira: 'くりすますそんぐ',
    singer: 'Backnumber',
    singerHira: 'ばっくなんばー',
    url: 'https://youtu.be/HoL1PbSyBI0?t=638',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'だれかおれをすきになれ',
    songHira: 'だれかおれをすきになれ',
    singer: 'ノリアキ',
    singerHira: 'のりあき',
    url: 'https://youtu.be/HoL1PbSyBI0?t=848',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '感電',
    songHira: 'かんでん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1009',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'WISH',
    songHira: 'うぃっしゅ',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1269',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'クリスマスキャロルの頃には',
    songHira: 'くりすますきゃろるのころには',
    singer: '稲垣潤一',
    singerHira: 'いながきじゅんいち',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1455',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: "Burnin'X'mas",
    songHira: 'ばーにんくりすます',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1636',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'Last Christmas',
    songHira: 'らすとくりすます',
    singer: 'Wham!',
    singerHira: 'わむ！',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1830',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'いつかのメリークリスマス',
    songHira: 'いつかのめりーくりすます',
    singer: "B'z",
    singerHira: 'びーず',
    url: 'https://youtu.be/HoL1PbSyBI0?t=1953',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'すてきなホリデイ',
    songHira: 'すてきなほりでい',
    singer: '竹内まりや',
    singerHira: 'たけうちまりや',
    url: 'https://youtu.be/HoL1PbSyBI0?t=2107',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King&Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/HoL1PbSyBI0?t=2285',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'Snow Dream',
    songHira: 'しょうどりーむ',
    singer: 'SnowMan',
    singerHira: 'すのーまん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=2575',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '若者のすべて',
    songHira: 'わかもののすべて',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/HoL1PbSyBI0?t=2830',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '二人のアカボシ',
    songHira: 'ふたりのあかぼし',
    singer: 'キンモクセイ',
    singerHira: 'きんもくせい',
    url: 'https://youtu.be/HoL1PbSyBI0?t=2998',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'くるみ',
    songHira: 'くるみ',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=3337',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'メリクリ',
    songHira: 'めりくり',
    singer: 'BoA',
    singerHira: 'ぼあ',
    url: 'https://youtu.be/HoL1PbSyBI0?t=3558',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'さよなら大好きな人',
    songHira: 'さよならだいすきなひと',
    singer: '花*花',
    singerHira: 'はな*はな',
    url: 'https://youtu.be/HoL1PbSyBI0?t=3785',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'ANOTHER WORLD',
    songHira: 'あなざーわーるど',
    singer: 'GACKT',
    singerHira: 'がくと',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4097',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'snow drop',
    songHira: 'すのーどろっぷ',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4191',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'Winter,again',
    songHira: 'うぃんたーあげいん',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4415',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '女々しくて',
    songHira: 'めめしくて',
    singer: 'ゴールデンボンバー',
    singerHira: 'ごーるでんぼんばー',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4565',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '今宵の月のように',
    songHira: 'こよいのつきのように',
    singer: 'エレファントカシマシ',
    singerHira: 'えれふぁんと かしまし',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4718',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'Dream',
    songHira: 'どりーむ',
    singer: '吉幾三',
    singerHira: 'よしいくぞう',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4891',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '世界はそれを愛と呼ぶんだぜ',
    songHira: 'せかいはそれをあいとよぶんだぜ',
    singer: 'サンボマスター',
    singerHira: 'さんぼますたー',
    url: 'https://youtu.be/HoL1PbSyBI0?t=4993',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '浪漫飛行',
    songHira: 'ろまんひこう',
    singer: '米米CLUB',
    singerHira: 'こめこめくらぶ',
    url: 'https://youtu.be/HoL1PbSyBI0?t=5216',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '線香',
    songHira: 'せんこう',
    singer: 'VB',
    singerHira: 'ぶいびー',
    url: 'https://youtu.be/HoL1PbSyBI0?t=5352',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '夕焼け小焼け',
    songHira: 'ゆうやけこやけ',
    singer: 'EIKO',
    singerHira: 'えいこ',
    url: 'https://youtu.be/HoL1PbSyBI0?t=5567',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '紅蓮花',
    songHira: 'ぐれんげ',
    singer: 'LiSA',
    singerHira: 'りさ',
    url: 'https://youtu.be/HoL1PbSyBI0?t=5853',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'Tomorrow never knows',
    songHira: 'とぅもろーねばーのうず',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6068',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '猫',
    songHira: 'ねこ',
    singer: 'DISH//',
    singerHira: 'でぃっしゅ',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6253',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'カナリヤ',
    songHira: 'かなりや',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6433',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '粉雪',
    songHira: 'こなゆき',
    singer: 'レミオロメン',
    singerHira: 'れみおろめん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6523',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: 'うちで踊ろう',
    songHira: 'うちでおどろう',
    singer: '星野源',
    singerHira: 'ほしのげん',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6753',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '愛のかたまり',
    songHira: 'あいのかたまり',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/HoL1PbSyBI0?t=6940',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/HoL1PbSyBI0?t=7163',
    thumbnails: 'https://img.youtube.com/vi/HoL1PbSyBI0/maxresdefault.jpg',
    title: '聖夜に防音室の性能を試したいVBのクリスマスカウントダウン三味線ライブ',
    date: '2020/12/24',
  },
];

export default L;
