const L: Array<Content> = [
  {
    song: '紅蓮華',
    songHira: 'ぐれんげ',
    singer: 'LiSA',
    singerHira: 'りさ',
    url: 'https://www.youtube.com/watch?v=1Y48lEUn0LY&t=744s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  // ry
  {
    song: '感電',
    songHira: 'かんでん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  {
    song: 'Pretender',
    songHira: 'ぷれてんだー',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  {
    song: 'Make you happy',
    songHira: 'めいくゆーはっぴー',
    singer: 'NiziU',
    singerHira: 'にじゅう',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  //ry
  {
    song: '愛を伝えたいだとか',
    songHira: 'あいをつたえたいだとか',
    singer: 'あいみょん',
    singerHira: 'あいみょん',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  //ry
  {
    song: '全力少年',
    songHira: 'ぜんりょくしょうねん',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  // ry
  {
    song: '硝子の少年',
    songHira: 'がらすのしょうねん',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://www.youtube.com/watch?v=1Y48lEUn0LY&t=744s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  {
    song: '恋の魔力',
    songHira: 'こいのまりょく',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  {
    song: 'ピースサイン',
    songHira: 'ぴーすさいん',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  // ry
  {
    song: 'ノーダウト',
    songHira: 'のーだうと',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  {
    song: "Don't Stop Me Now",
    songHira: 'どんとすとっぷみーなう',
    singer: 'QUEEN',
    singerHira: 'くいーん',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  //ry
  {
    song: '真夏の果実',
    songHira: 'まなつのかじつ',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
  //ry
  {
    song: 'Rising Hope',
    songHira: 'らいじんぶほーぷ',
    singer: 'LiSA',
    singerHira: 'りさ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/1Y48lEUn0LY/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのモチベが上がる曲弾き語り三味線ライブ',
    date: '2020/07/31',
  },
];

export default L;
