const L: Array<Content> = [
  {
    song: '生きてることが辛いなら',
    songHira: 'いきてることがつらいなら',
    singer: ' 森山直太朗',
    singerHira: 'もりやまなおたろう',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=58',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '僕が死のうと思ったのは',
    songHira: 'ぼくがしのうとおもったのは',
    singer: ' 中島美嘉',
    singerHira: 'なかじまみか',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=318',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '生きていたんだよな',
    songHira: 'いきていたんだよな',
    singer: ' あいみょん',
    singerHira: 'あいみょん',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=625',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'さよならエレジー',
    songHira: 'さよならえれじー',
    singer: ' 菅田将暉',
    singerHira: 'すげたまさき',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=796',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '十戒',
    songHira: 'じっかい',
    singer: ' 中森明菜',
    singerHira: 'なかもりあきな',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=994',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '神田川',
    songHira: 'かんだがわ',
    singer: ' かぐや姫',
    singerHira: 'かぐやひめ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=1163',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '海の幽霊',
    songHira: 'うみのゆうれい',
    singer: ' 米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=1391',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '丸の内サディスティック',
    songHira: 'まるのうちさでぃすてぃっく',
    singer: ' 椎名林檎',
    singerHira: 'しいなりんご',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=1589',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '田園',
    songHira: 'でんえん',
    singer: ' 玉置浩二',
    singerHira: 'たまきこうじ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=1733',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'シーソーゲーム',
    songHira: 'しーそーげーむ',
    singer: ' Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=1924',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'ノーダウト',
    songHira: 'のーだうと',
    singer: ' Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2149',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '雨のち晴レルヤ',
    songHira: 'あめのちはれれるや',
    singer: ' ゆず',
    singerHira: 'ゆず',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2274',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'うちでババろう',
    songHira: 'うちでばばろう',
    singer: 'VB',
    singerHira: 'ばーちゃるおばあちゃん',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2426',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '1/3の純情な感情',
    songHira: '1/3のじゅんじょうなかんじょう',
    singer: 'SIAM SHADE',
    singerHira: 'しゃむしぇいど',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2566',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'こころはタマゴ',
    songHira: 'こころはたまご',
    singer: ' 影山ヒロノブ',
    singerHira: 'かげやまひろのぶ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2753',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '世界が終るまでは…',
    songHira: 'せかいが おわるまでは…',
    singer: ' WANDS',
    singerHira: 'わんず',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2823',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '赤黄色の金木犀',
    songHira: 'あかきいろの きんもくせい',
    singer: ' フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=2986',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'Colors of the Heart',
    songHira: 'からーずおぶざはーと',
    singer: ' UVERworld',
    singerHira: 'うーばーわーるど',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3210',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '愛燦燦',
    songHira: 'あいさんさん',
    singer: ' 美空ひばり',
    singerHira: 'みそらひばり',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3406',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '傘がない',
    songHira: 'かさがない',
    singer: ' 井上陽水',
    singerHira: 'いのうえようすい',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3536',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: ' King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3645',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '北の国から',
    songHira: 'きたのくにから',
    singer: ' さだまさし',
    singerHira: 'さだまさし',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3841',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '今宵の月のように',
    songHira: 'こよいのつきのように',
    singer: ' エレファントカシマシ',
    singerHira: 'えれふぁんとかしまし',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=3865',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '母に捧げるバラード',
    songHira: 'ははにささげるばらーど',
    singer: ' 海援隊',
    singerHira: 'かいえんたい',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=4038',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'セロリ',
    songHira: 'せろり',
    singer: ' SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=4260',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'R.Y.U.S.E.I.',
    songHira: 'りゅうせい',
    singer: ' 三代目 J Soul Brothers from EXILE TRIBE',
    singerHira: 'さんだいめ じぇーそうるぶらざーず',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=4447',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '瞳の住人',
    songHira: 'ひとみのじゅうにん',
    singer: " L'Arc~en~Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=4674',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'Rain',
    songHira: 'れいん',
    singer: '大江千里',
    singerHira: 'おおえせんり',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=4923',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '月とナイフ',
    songHira: 'つきとないふ',
    singer: ' スガシカオ',
    singerHira: 'すがしかお',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=5089',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'あの日に帰りたい',
    songHira: 'あのひにかえりたい',
    singer: ' 荒井由実',
    singerHira: 'あらいゆみ',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=5308',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: 'ガッツだぜ！！',
    songHira: 'がっつだぜ！！',
    singer: ' ウルフルズ',
    singerHira: 'うるふるず',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=5464',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/AEVB3vaI1Ng?t=5555',
    thumbnails: 'https://img.youtube.com/vi/AEVB3vaI1Ng/maxresdefault.jpg',
    title: '鬱なときに聴きたい……VBの五月病リラクゼーション三味線ライブ',
    date: '2020/05/08',
  },
];

export default L;
