const L: Array<Content> = [
  {
    song: 'フレンズ',
    songHira: 'ふれんず',
    singer: 'レベッカ',
    singerHira: 'れべっか',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'きらり',
    songHira: 'きらり',
    singer: '藤井風',
    singerHira: 'ふじいかぜ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'うっせえわ',
    songHira: 'うっせえわ',
    singer: 'Ado',
    singerHira: 'あど',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Shangri-La',
    songHira: 'しゃんぐりら',
    singer: '電気グルーヴ',
    singerHira: 'でんきぐるーゔ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'ダイナマイト',
    songHira: 'だいなまいと',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Dynamite',
    songHira: 'だいなまいと',
    singer: 'BTS',
    singerHira: 'びーてぃーえす',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King & Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'POISON',
    songHira: 'ぽいずん',
    singer: '反町隆史',
    singerHira: 'そりまちたかし',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  // ry
  {
    song: '猫',
    songHira: 'ねこ',
    singer: 'BiSH',
    singerHira: 'びっしゅ',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  // ry
  {
    song: '歩いて帰ろう',
    songHira: 'あるいてかえろう',
    singer: '斉藤和義',
    singerHira: 'さいとうかずよし',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'HANABI',
    songHira: 'はなび',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  // ry
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国家',
    singerHira: 'こっか',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '愛はおしゃれじゃない',
    songHira: 'あいはおしゃれじゃない',
    singer: '岡村靖幸',
    singerHira: 'おかむらやすゆき',
    url: 'https://www.youtube.com/watch?v=SQlFFjXHne4&t=5318s',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
];

export default L;
