const L: Array<Content> = [
  {
    song: 'ボーイフレンド',
    songHira: 'ぼーいふれんど',
    singer: 'aiko',
    singerHira: 'あいこ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=36',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '可愛いミーナ',
    songHira: 'かわいいみーな',
    singer: '桑田佳祐',
    singerHira: 'くわたけいすけ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=296',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'M',
    songHira: 'えむ',
    singer: 'プリンセスプリンセス',
    singerHira: 'ぷりんせすぷりんせす',
    url: 'https://youtu.be/BHWJDfoMbO8?t=500',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Cry Baby',
    songHira: 'くらいべいびー',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=622',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Pretender',
    songHira: 'ぷれてんだー',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=857',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'CHE.R.RY',
    songHira: 'ちぇりー',
    singer: 'YUI',
    singerHira: 'ゆい',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1111',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '月光',
    songHira: 'げっこう',
    singer: '鬼束ちひろ',
    singerHira: 'おにつかちひろ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1253',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Darling',
    songHira: 'だーりん',
    singer: 'V6',
    singerHira: 'ぶいしっくす',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1425',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Thaï nana',
    songHira: 'たいなな',
    singer: 'Kazero',
    singerHira: 'かぜろ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1590',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Dynamite',
    songHira: 'だいなまいと',
    singer: 'BTS',
    singerHira: 'びーてぃーえす',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1624',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '初恋LOVE',
    songHira: 'うぶらぶ',
    singer: 'なにわ男子',
    singerHira: 'なにわだんし',
    url: 'https://youtu.be/BHWJDfoMbO8?t=1908',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'First Love',
    songHira: 'ふぁーすとらぶ',
    singer: '宇多田ヒカル',
    singerHira: 'うただひかる',
    url: 'https://youtu.be/BHWJDfoMbO8?t=2180',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'チェリー',
    songHira: 'ちぇりー',
    singer: 'スピッツ',
    singerHira: 'すぴっつ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=2386',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'One more time, One more chance ',
    songHira: 'わんもあたいむわんもあちゃんす',
    singer: '山崎まさよし',
    singerHira: 'やまざきまさよし',
    url: 'https://youtu.be/BHWJDfoMbO8?t=2583',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'プラネタリウム',
    songHira: 'ぷらねたりうむ',
    singer: '大塚愛',
    singerHira: 'おおつかあい',
    url: 'https://youtu.be/BHWJDfoMbO8?t=2728',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '好き好き大好き',
    songHira: 'すきすきだいすき',
    singer: '戸川純',
    singerHira: 'とがわじゅん',
    url: 'https://youtu.be/BHWJDfoMbO8?t=2915',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'だいすき',
    songHira: 'だいすき',
    singer: '岡村靖幸',
    singerHira: 'おかむらやすゆき',
    url: 'https://youtu.be/BHWJDfoMbO8?t=3028',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '高嶺の花子さん',
    songHira: 'たかせのはなこさん',
    singer: 'Back number',
    singerHira: 'ばっくなんばー',
    url: 'https://youtu.be/BHWJDfoMbO8?t=3281',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'きらり',
    songHira: 'きらり',
    singer: '藤井風',
    singerHira: 'ふじいかぜ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=3442',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Revival',
    songHira: 'りばいばる',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/BHWJDfoMbO8?t=3686',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '願い',
    songHira: 'ねがい',
    singer: 'sumika',
    singerHira: 'すみか',
    url: 'https://youtu.be/BHWJDfoMbO8?t=3892',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'Make you happy',
    songHira: 'めいくゆーはっぴー',
    singer: 'NiziU',
    singerHira: 'にじゅう',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4072',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '愛の才能',
    songHira: 'あいのさいのう',
    singer: '川本真琴',
    singerHira: 'かわもとまこと',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4211',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'ぼくらが旅に出る理由',
    songHira: 'ぼくらがたびにでるりゆう',
    singer: '小沢健二',
    singerHira: 'おざわけんじ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4409',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'シーソーゲーム',
    songHira: 'しーそーげーむ',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4541',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '愛されるより 愛したい',
    songHira: 'あいされるよりあいしたい',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4679',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'まちがいさがし',
    songHira: 'まちがいさがし',
    singer: '菅田将暉',
    singerHira: 'すだまさき',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4810',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'まちがいさがし (サビ)',
    songHira: 'まちがいさがし',
    singer: '菅田将暉',
    singerHira: 'すだまさき',
    url: 'https://youtu.be/BHWJDfoMbO8?t=4946',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'TSUNAMI',
    songHira: 'つなみ',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/BHWJDfoMbO8?t=5144',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'ファンタスティポ',
    songHira: 'ふぁんたすてぃぽ',
    singer: 'トラジ・ハイジ',
    singerHira: 'とらじはいじ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=5336',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '君は薔薇より美しい',
    songHira: 'きみはばらよりもうつくしい',
    singer: '布施明',
    singerHira: 'ふせあきら',
    url: 'https://youtu.be/BHWJDfoMbO8?t=5513',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国家',
    singerHira: 'こっか',
    url: 'https://youtu.be/BHWJDfoMbO8?t=5602',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King & Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/BHWJDfoMbO8?t=5689',
    thumbnails: 'https://img.youtube.com/vi/BHWJDfoMbO8/maxresdefault.jpg',
    title: '失恋女子集まれ！！自己肯定感をアレするためのリクエスト三味線ライブ',
    date: '2021/12/03',
  },
];

export default L;
