const L: Array<Content> = [
  {
    song: 'かもめが翔んだ日',
    songHira: 'かもめがとんだひ',
    singer: '渡辺真知子',
    singerHira: 'わたなべまちこ',
    url: 'https://youtu.be/BHWJDfoMbO8?t=33',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '勝手にしやがれ',
    songHira: 'かってにしやがれ',
    singer: '沢田研二',
    singerHira: 'さわだけんじ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=296',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'よろしく哀愁',
    songHira: 'よろしくあいしゅう',
    singer: '郷ひろみ',
    singerHira: 'ごうひろみ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=507',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'プレイバック Part2',
    songHira: 'ぷれいばっくぱーと2',
    singer: '山口百恵',
    singerHira: 'やまぐちももえ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=668',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '木綿のハンカチーフ',
    songHira: 'もめんのはんかちーふ',
    singer: '太田裕美',
    singerHira: 'おおたひろみ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=863',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '慟哭',
    songHira: 'どうこく',
    singer: '工藤静香',
    singerHira: 'くどうしずか',
    url: 'https://youtu.be/nd8QMz7H7YI?t=996',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '神田川',
    songHira: 'かんだがわ',
    singer: '南こうせつ',
    singerHira: 'みなみこうせつ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1173',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '夢の中へ',
    songHira: 'ゆめのなかへ',
    singer: '井上陽水',
    singerHira: 'いのうえようすい',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1345',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '十戒',
    songHira: 'じっかい',
    singer: '中森明菜',
    singerHira: 'なかもりあきな',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1498',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'ルビーの指環',
    songHira: 'るびーのゆびわ',
    singer: '寺尾聰',
    singerHira: 'てらおあきら',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1644',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '贈る言葉',
    songHira: 'おくることば',
    singer: '海援隊',
    singerHira: 'かいえんたい',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1787',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '船唄',
    songHira: 'ふねうた',
    singer: '八代亜紀',
    singerHira: 'やしろあき',
    url: 'https://youtu.be/nd8QMz7H7YI?t=1912',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '川の流れのように',
    songHira: 'かわのながれのように',
    singer: '美空ひばり',
    singerHira: 'みそらひばり',
    url: 'https://youtu.be/nd8QMz7H7YI?t=2091',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '銀河鉄道999',
    songHira: 'ぎんがてつどうすりーないん',
    singer: 'ゴダイゴ',
    singerHira: 'ごだいご',
    url: 'https://youtu.be/nd8QMz7H7YI?t=2427',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '喝采',
    songHira: 'かっさい',
    singer: 'ちあきなおみ',
    singerHira: 'ちあきなおみ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=2566',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'ワインレッドの心',
    songHira: 'わいんれっどのこころ',
    singer: '安全地帯',
    singerHira: 'あんぜんちたい',
    url: 'https://youtu.be/nd8QMz7H7YI?t=2744',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'フライディ・チャイナタウン',
    songHira: 'ふらいでぃちゃいなたうん',
    singer: '泰葉',
    singerHira: 'やすは',
    url: 'https://youtu.be/nd8QMz7H7YI?t=2901',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '異邦人',
    songHira: 'いほうじん',
    singer: '久保田早紀',
    singerHira: 'くぼたさき',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3080',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'あなた',
    songHira: 'あなた',
    singer: '小坂明子',
    singerHira: 'こさかあきこ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3220',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '赤いスイートピー',
    songHira: 'あかいすいーとぴー',
    singer: '松田聖子',
    singerHira: 'まつだせいこ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3406',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'あの素晴らしい愛をもう一度',
    songHira: 'あのすばらしいあいをもういちど',
    singer: '北山修',
    singerHira: 'きたやまおさむ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3572',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '中央フリーウェイ',
    songHira: 'ちゅうおうふりーうぇい',
    singer: '松任谷由実',
    singerHira: 'まつとうやゆみ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3736',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'おふくろさん',
    songHira: 'おふくろさん',
    singer: '森進一',
    singerHira: 'もりしんいち',
    url: 'https://youtu.be/nd8QMz7H7YI?t=3915',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'きみは薔薇より美しい',
    songHira: 'きみはばらよりうつくしい',
    singer: '布施明',
    singerHira: 'ふせあきら',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4040',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '時の過ぎゆくままに',
    songHira: 'ときのすぎゆくままに',
    singer: '沢田研二',
    singerHira: 'たきざわけんじ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4161',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'イミテイション・ゴールド',
    songHira: 'いみていしょんごーるど',
    singer: '山口百恵',
    singerHira: 'やまぐちももえ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4287',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '関白宣言',
    songHira: 'かんぱくせんげん',
    singer: 'さだまさし',
    singerHira: 'さだまさし',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4454',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '接吻',
    songHira: 'せっぷん',
    singer: 'ORIGINAL LOVE',
    singerHira: 'おりじなるらぶ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4616',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'Get Wild',
    songHira: 'げっとわいるど',
    singer: 'TM NETWORK',
    singerHira: 'てぃーえむねっとわーく',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4737',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'だいすき',
    songHira: 'だいすき',
    singer: '岡村靖幸',
    singerHira: 'おかむらやすゆき',
    url: 'https://youtu.be/nd8QMz7H7YI?t=4893',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '昴',
    songHira: 'すばる',
    singer: '谷村新司',
    singerHira: 'たにむらしんじ',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5071',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'Beautiful World',
    songHira: 'びゅーてぃふるわーるど',
    singer: '宇多田ヒカル',
    singerHira: 'うただひかる',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5200',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '恋人',
    songHira: 'こいびと',
    singer: '鈴木雅之',
    singerHira: 'すずきまさゆき',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5466',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'およげ！たいやきくん アカペラver',
    songHira: 'およげ！たいやきくん',
    singer: '子門真人',
    singerHira: 'しもんまさと',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5674',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'およげ！たいやきくん',
    songHira: 'およげ！たいやきくん',
    singer: '子門真人',
    singerHira: 'しもんまさと',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5758',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'さそり座の女',
    songHira: 'さそりざのおんな',
    singer: '美川憲一',
    singerHira: 'みかわけんいち',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5887',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '詠人',
    songHira: 'うたびと',
    singer: '北島三郎',
    singerHira: 'きたじまさぶろう',
    url: 'https://youtu.be/nd8QMz7H7YI?t=5992',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: 'いとしのエリー',
    songHira: 'いとしのえりー',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/nd8QMz7H7YI?t=6173',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '上を向いて歩こう',
    songHira: 'うえをむいてあるこう',
    singer: '坂本九',
    singerHira: 'さかもときゅう',
    url: 'https://youtu.be/nd8QMz7H7YI?t=6347',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/nd8QMz7H7YI?t=6474',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
  {
    song: '愛のメモリー',
    songHira: 'あいのめもりー',
    singer: '松崎しげる',
    singerHira: 'まつざきしげる',
    url: 'https://youtu.be/nd8QMz7H7YI?t=6578',
    thumbnails: 'https://img.youtube.com/vi/nd8QMz7H7YI/maxresdefault.jpg',
    title: '昭和が一番良かった。【バーチャルおばあちゃんの昭和歌謡三味線ライブ】',
    date: '2021/04/09',
  },
];

export default L;
