const L: Array<Content> = [
  {
    song: 'フレンズ',
    songHira: 'ふれんず',
    singer: 'レベッカ',
    singerHira: 'れべっか',
    url: 'https://youtu.be/SQlFFjXHne4?t=55',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '白日',
    songHira: 'はくじつ',
    singer: 'King Gnu',
    singerHira: 'きんぐぬー',
    url: 'https://youtu.be/SQlFFjXHne4?t=320',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'きらり',
    songHira: 'きらり',
    singer: '藤井風',
    singerHira: 'ふじいかぜ',
    url: 'https://youtu.be/SQlFFjXHne4?t=527',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'うっせぇわ',
    songHira: 'うっせぇわ',
    singer: 'Ado',
    singerHira: 'あど',
    url: 'https://youtu.be/SQlFFjXHne4?t=760',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Shangri-La',
    songHira: 'しゃんぐりら',
    singer: '電気グルーヴ',
    singerHira: 'でんきぐるーゔ',
    url: 'https://youtu.be/SQlFFjXHne4?t=947',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'ダイナマイト',
    songHira: 'だいなまいと',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/SQlFFjXHne4?t=1106',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Dynamite',
    songHira: 'だいなまいと',
    singer: 'BTS',
    singerHira: 'びーてぃーえす',
    url: 'https://youtu.be/SQlFFjXHne4?t=1268',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King & Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/SQlFFjXHne4?t=1504',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'POISON~言いたいことも言えないこんな世の中は~',
    songHira: 'ぽいずん いいたい ことも いえない こんな よのなかは',
    singer: '反町隆史',
    singerHira: 'そりまちたかし',
    url: 'https://youtu.be/SQlFFjXHne4?t=1717',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'ギザギザハートの子守唄',
    songHira: 'ぎざぎざはーとのこもりうた',
    singer: 'チェッカーズ',
    singerHira: 'ちぇっかーず',
    url: 'https://youtu.be/SQlFFjXHne4?t=1843',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'MARIONETTE',
    songHira: 'まりおねっと',
    singer: 'BOØWY',
    singerHira: 'ぼうい',
    url: 'https://youtu.be/SQlFFjXHne4?t=2091',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '世界はそれを愛と呼ぶんだぜ',
    songHira: 'せかいはそれをあいとよぶんだぜ',
    singer: 'サンボマスター',
    singerHira: 'さんぼますたー',
    url: 'https://youtu.be/SQlFFjXHne4?t=2245',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Gang⭐︎',
    songHira: 'ぎゃんぐ︎',
    singer: '福山雅治',
    singerHira: 'ふくやままさはる',
    url: 'https://youtu.be/SQlFFjXHne4?t=2437',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Pretender',
    songHira: 'ぷれてんだー',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/SQlFFjXHne4?t=2671',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'オーケストラ',
    songHira: 'おーけすとら',
    singer: 'BiSH',
    singerHira: 'びっしゅ',
    url: 'https://youtu.be/SQlFFjXHne4?t=2930',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '猫',
    songHira: 'ねこ',
    singer: 'DISH//',
    singerHira: 'でぃっしゅ',
    url: 'https://youtu.be/SQlFFjXHne4?t=3032',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'secret base ~君がくれたもの~',
    songHira: 'しーくれっとべーすきみがくれたもの',
    singer: 'ZONE',
    singerHira: 'ぞーん',
    url: 'https://youtu.be/SQlFFjXHne4?t=3183',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Camera! Camera! Camera! ',
    songHira: 'かめらかめらかめら',
    singer: 'フリッパーズ・ギター',
    singerHira: 'ふりっぱーずぎたー',
    url: 'https://youtu.be/SQlFFjXHne4?t=3377',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'A Perfect Sky',
    songHira: 'あぱーふぇくとすかい',
    singer: 'BONNIE PINK',
    singerHira: 'ぼにーぴんく',
    url: 'https://youtu.be/SQlFFjXHne4?t=3503',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '夏の日の1993',
    songHira: 'なつのひの1933',
    singer: 'Class',
    singerHira: 'くらす',
    url: 'https://youtu.be/SQlFFjXHne4?t=3703',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'Self Control',
    songHira: 'せるふこんとろーる',
    singer: 'TM NETWORK',
    singerHira: 'てぃーえむねっとわーく',
    url: 'https://youtu.be/SQlFFjXHne4?t=3887',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '歩いて帰ろう',
    songHira: 'あるいてかえろう',
    singer: '斉藤和義',
    singerHira: 'さいとうかずよし',
    url: 'https://youtu.be/SQlFFjXHne4?t=4040',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'HANABI',
    songHira: 'はなび',
    singer: 'Mr.Children',
    singerHira: 'みすたーちるどれん',
    url: 'https://youtu.be/SQlFFjXHne4?t=4242',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '若者のすべて',
    songHira: 'わかもののすべて',
    singer: 'フジファブリック',
    singerHira: 'ふじふぁぶりっく',
    url: 'https://youtu.be/SQlFFjXHne4?t=4473',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'サマーヌード',
    songHira: 'さまーぬーど',
    singer: '真心ブラザーズ',
    singerHira: 'まごころぶらざーず',
    url: 'https://youtu.be/SQlFFjXHne4?t=4712',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'HOT LIMIT',
    songHira: 'ほっとりみっと',
    singer: 'T.M.Revolution',
    singerHira: 'てぃーえむれぼりゅーしょん',
    url: 'https://youtu.be/SQlFFjXHne4?t=4922',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '真夏の果実',
    songHira: 'まなつの かじつ',
    singer: 'サザンオールスターズ',
    singerHira: 'さざんおーるすたーず',
    url: 'https://youtu.be/SQlFFjXHne4?t=5073',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '接吻',
    songHira: 'せっぷん',
    singer: 'ORIGINAL LOVE',
    singerHira: 'おりじなるらぶ',
    url: 'https://youtu.be/SQlFFjXHne4?t=5336',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: "Driver's High",
    songHira: 'どらいばーずはい',
    singer: "L'Arc〜en〜Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/SQlFFjXHne4?t=5614',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'ジェットコースター・ロマンス',
    songHira: 'じぇっとこーすたー・ろまんす',
    singer: 'KinKi Kids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/SQlFFjXHne4?t=5808',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: 'サマータイムラブ',
    songHira: 'さまーたいむらぶ',
    singer: 'Shiggy Jr.',
    singerHira: 'しぎーじゅにあ',
    url: 'https://youtu.be/SQlFFjXHne4?t=6036',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/SQlFFjXHne4?t=6144',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
  {
    song: '愛はおしゃれじゃない',
    songHira: 'あいはおしゃれじゃない',
    singer: '岡村靖幸',
    singerHira: 'おかむらやすゆき',
    url: 'https://youtu.be/SQlFFjXHne4?t=6248',
    thumbnails: 'https://img.youtube.com/vi/SQlFFjXHne4/maxresdefault.jpg',
    title: 'ババロックフェスティバル2021【リクエスト参加型三味線ライブ】',
    date: '2021/08/24',
  },
];

export default L;
