const L: Array<Content> = [
  {
    song: 'クリスマス・イブ',
    songHira: 'くりすます・いぶ',
    singer: '山下達郎',
    singerHira: 'やましたたつろう',
    url: 'https://youtu.be/b01cFxs8HRE&t=59',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'クリスマスキャロルの頃には',
    songHira: 'くりすますきゃろるのころには',
    singer: '稲垣潤一',
    singerHira: 'いながきじゅんいち',
    url: 'https://youtu.be/b01cFxs8HRE&t=494',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'シンデレラ･クリスマス',
    songHira: 'しんでれら･くりすます',
    singer: 'KinKiKids（with五月雨空也）',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/b01cFxs8HRE&t=1104',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'シンデレラ･クリスマス',
    songHira: 'しんでれら･くりすます',
    singer: 'KinKiKids',
    singerHira: 'きんききっず',
    url: 'https://youtu.be/b01cFxs8HRE&t=1493',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'メリクリ',
    songHira: 'めりくり',
    singer: 'BoA',
    singerHira: 'ぼあ',
    url: 'https://youtu.be/b01cFxs8HRE&t=1926',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '君が好きだと叫びたい',
    songHira: 'きみがすきだとさけびたい',
    singer: 'BAAD',
    singerHira: 'ばーど',
    url: 'https://youtu.be/b01cFxs8HRE&t=2131',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '粉雪',
    songHira: 'こなゆき',
    singer: 'レミオロメン',
    singerHira: 'れみおろめん',
    url: 'https://youtu.be/b01cFxs8HRE&t=2307',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'Subtitle',
    songHira: 'さぶたいとる',
    singer: 'Official髭男dism',
    singerHira: 'おふぃしゃるひげだんでぃずむ',
    url: 'https://youtu.be/b01cFxs8HRE&t=2586',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'KICKBACK',
    songHira: 'きっくばっく',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/b01cFxs8HRE&t=2807',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '白い恋人達',
    songHira: 'しろいこいびとたち',
    singer: '桑田佳祐',
    singerHira: 'くわたけいすけ',
    url: 'https://youtu.be/b01cFxs8HRE&t=2997',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '冬がはじまるよ',
    songHira: 'ふゆがはじまるよ',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/b01cFxs8HRE&t=3191',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'らいおんハート',
    songHira: 'らいおんはーと',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/b01cFxs8HRE&t=3232',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'チキンライス',
    songHira: 'ちきんらいす',
    singer: '槇原敬之',
    singerHira: 'まきはらのりゆき',
    url: 'https://youtu.be/b01cFxs8HRE&t=3421',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'いつかのメリークリスマス',
    songHira: 'いつかのめりーくりすます',
    singer: 'B’z',
    singerHira: 'びーず',
    url: 'https://youtu.be/b01cFxs8HRE&t=3573',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'メヌエット',
    songHira: 'めぬえっと',
    singer: '山崎まさよし',
    singerHira: 'やまざきまさよし',
    url: 'https://youtu.be/b01cFxs8HRE&t=3756',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'LastChristmas',
    songHira: 'らすとくりすます',
    singer: 'Wham!',
    singerHira: 'わむ',
    url: 'https://youtu.be/b01cFxs8HRE&t=3906',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '勝手にしやがれ',
    songHira: 'かってにしやがれ',
    singer: '沢田研二',
    singerHira: 'さわだけんじ',
    url: 'https://youtu.be/b01cFxs8HRE&t=4075',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '夜空ノムコウ',
    songHira: 'よぞらのむこう',
    singer: 'SMAP',
    singerHira: 'すまっぷ',
    url: 'https://youtu.be/b01cFxs8HRE&t=4227',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '最初から今まで',
    songHira: 'さいしょからいままで',
    singer: 'Ryu',
    singerHira: 'りゅ',
    url: 'https://youtu.be/b01cFxs8HRE&t=4533',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'Dynamite',
    songHira: 'だいなまいと',
    singer: 'BTS',
    singerHira: 'びーてぃーえす',
    url: 'https://youtu.be/b01cFxs8HRE&t=4664',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'Winter,again',
    songHira: 'うぃんたー,あげいん',
    singer: 'GLAY',
    singerHira: 'ぐれい',
    url: 'https://youtu.be/b01cFxs8HRE&t=4847',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'winterfall',
    songHira: 'うぃんたーふぉーる',
    singer: "L'Arc~en~Ciel",
    singerHira: 'らるくあんしえる',
    url: 'https://youtu.be/b01cFxs8HRE&t=5064',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'ナンダカンダ',
    songHira: 'なんだかんだ',
    singer: '藤井隆',
    singerHira: 'ふじいたかし',
    url: 'https://youtu.be/b01cFxs8HRE&t=5277',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: 'ナンダカンダ（with五月雨空也）',
    songHira: 'なんだかんだ',
    singer: '藤井隆',
    singerHira: 'ふじいたかし',
    url: 'https://youtu.be/b01cFxs8HRE&t=5418',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
  {
    song: '君が代（with五月雨空也）',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: 'こっか',
    url: 'https://youtu.be/b01cFxs8HRE&t=5473',
    thumbnails: 'https://img.youtube.com/vi/b01cFxs8HRE/maxresdefault.jpg',
    title: 'バーチャルおばあちゃんのクリスマス三味線弾き語りライブ2022',
    date: '2022/12/24',
  },
];

export default L;
