const L: Array<Content> = [
  {
    song: 'SweetLove',
    songHira: 'すいーとらぶ',
    singer: "ときめきメモリアルGirl'sSide4thHeart",
    singerHira: 'ときめきめもりある',
    url: 'https://youtu.be/Whj85bHTRqU&t=41',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'ダイヤモンドスマイル',
    songHira: 'だいやもんどすまいる',
    singer: 'なにわ男子',
    singerHira: 'なにわだんし',
    url: 'https://youtu.be/Whj85bHTRqU&t=472',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'MeltyLove',
    songHira: 'めるてぃーらぶ',
    singer: 'SHAZNA',
    singerHira: 'しゃずな',
    url: 'https://youtu.be/Whj85bHTRqU&t=720',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'やさしい気持ち',
    songHira: 'やさしいきもち',
    singer: 'CHARA',
    singerHira: 'ちゃら',
    url: 'https://youtu.be/Whj85bHTRqU&t=995',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '命に嫌われている',
    songHira: 'いのちにきらわれている',
    singer: 'カンザキイオリ',
    singerHira: 'かんざきいおり',
    url: 'https://youtu.be/Whj85bHTRqU&t=1087',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'POISON~言いたい事も言えないこんな世の中は~(hydever.)',
    songHira: 'ぽいずん~いいたいこともいえないこんなよのなかは',
    singer: '反町隆史',
    singerHira: 'そりまちたかし',
    url: 'https://youtu.be/Whj85bHTRqU&t=1300',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'Glass',
    songHira: 'ぐらす',
    singer: '河村隆一',
    singerHira: 'かわむらりゅういち',
    url: 'https://youtu.be/Whj85bHTRqU&t=1404',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'ドライフラワー',
    songHira: 'どらいふらわー',
    singer: '優里',
    singerHira: 'ゆうり',
    url: 'https://youtu.be/Whj85bHTRqU&t=1491',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'Stay',
    songHira: 'すてい',
    singer: '大浦祐一',
    singerHira: 'おおうらゆういち',
    url: 'https://youtu.be/Whj85bHTRqU&t=1640',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '君が好きだと叫びたい',
    songHira: 'きみがすきだとさけびたい',
    singer: 'BAAD',
    singerHira: 'ばーど',
    url: 'https://youtu.be/Whj85bHTRqU&t=1701',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'マイフレンド',
    songHira: 'まいふれんど',
    singer: 'ZARD',
    singerHira: 'ざーど',
    url: 'https://youtu.be/Whj85bHTRqU&t=1920',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'それじゃあバイバイ',
    songHira: 'それじゃあばいばい',
    singer: 'SURFACE',
    singerHira: 'さーふぇす',
    url: 'https://youtu.be/Whj85bHTRqU&t=2122',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'ブラザービート',
    songHira: 'ぶらざーびーと',
    singer: 'SnowMan',
    singerHira: 'すのーまん',
    url: 'https://youtu.be/Whj85bHTRqU&t=2371',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'Lovesosweet',
    songHira: 'らぶそーすうぃーと',
    singer: '嵐',
    singerHira: 'あらし',
    url: 'https://youtu.be/Whj85bHTRqU&t=2602',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'Moonlight…Silence…',
    songHira: 'むーんらいと…さいれんす…',
    singer: '緑川光',
    singerHira: 'みどりがわひかる',
    url: 'https://youtu.be/Whj85bHTRqU&t=2834',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '夢であるように',
    songHira: 'ゆめであるように',
    singer: 'ft.緑川光(sasakure.Arrangever.)fromテイルズオブディスティニー',
    singerHira: 'みどりがわひかる',
    url: 'https://youtu.be/Whj85bHTRqU&t=2899',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'ロビンソン',
    songHira: 'ろびんそん',
    singer: 'スピッツ',
    singerHira: 'すぴっつ',
    url: 'https://youtu.be/Whj85bHTRqU&t=3127',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'アゲハ蝶',
    songHira: 'あげはちょう',
    singer: 'ポルノグラフィティ',
    singerHira: 'ぽるのぐらふぃてぃ',
    url: 'https://youtu.be/Whj85bHTRqU&t=3290',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'サウダージ',
    songHira: 'さうだーじ',
    singer: 'ポルノグラフィティ',
    singerHira: 'ぽるのぐらふぃてぃ',
    url: 'https://youtu.be/Whj85bHTRqU&t=3407',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '大スキ!',
    songHira: 'だいすき!',
    singer: '広末涼子',
    singerHira: 'ひろすえりょうこ',
    url: 'https://youtu.be/Whj85bHTRqU&t=3494',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'MajiでKoiする5秒前',
    songHira: 'まじでこいするごびょうまえ',
    singer: '広末涼子',
    singerHira: 'ひろすえりょうこ',
    url: 'https://youtu.be/Whj85bHTRqU&t=3530',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '夕焼け小焼け',
    songHira: 'ゆうやけこやけ',
    singer: 'EIKO',
    singerHira: 'えいこー',
    url: 'https://youtu.be/Whj85bHTRqU&t=3720',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '小さな恋のうた',
    songHira: 'ちいさなこいのうた',
    singer: 'MONGOL800',
    singerHira: 'もんごるはっぴゃく',
    url: 'https://youtu.be/Whj85bHTRqU&t=4005',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'SecretTouch',
    songHira: 'しーくれっとたっち',
    singer: 'SnowMan',
    singerHira: 'すのーまん',
    url: 'https://youtu.be/Whj85bHTRqU&t=4060',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '十四時過ぎのカゲロウ',
    songHira: 'じゅうよじすぎのかげろう',
    singer: 'キリンジ',
    singerHira: 'きりんじ',
    url: 'https://youtu.be/Whj85bHTRqU&t=4118',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'エイリアンズ',
    songHira: 'えいりあんず',
    singer: 'キリンジ',
    singerHira: 'きりんじ',
    url: 'https://youtu.be/Whj85bHTRqU&t=4214',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '夢で逢えたら',
    songHira: 'ゆめであえたら',
    singer: '大滝詠一',
    singerHira: 'おおたきえいいち',
    url: 'https://youtu.be/Whj85bHTRqU&t=4285',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'ブルーでハッピーがいい',
    songHira: 'ぶるーではっぴーがいい',
    singer: 'ショコラ',
    singerHira: 'しょこら',
    url: 'https://youtu.be/Whj85bHTRqU&t=4456',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '田園(御影小次郎ver.)',
    songHira: 'でんえん',
    singer: '玉置浩二',
    singerHira: 'たまきこうじ',
    url: 'https://youtu.be/Whj85bHTRqU&t=4681',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '恋音と雨空',
    songHira: 'こいおんとあまぞら',
    singer: 'AAA',
    singerHira: 'とりぷるえー',
    url: 'https://youtu.be/Whj85bHTRqU&t=4890',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '永遠より続くように',
    songHira: 'えいえんよりつづくように',
    singer: 'OKL48',
    singerHira: 'おーけーえるふぉーてぃーえいと',
    url: 'https://youtu.be/Whj85bHTRqU&t=5106',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '奏',
    songHira: 'かなで',
    singer: 'スキマスイッチ',
    singerHira: 'すきますいっち',
    url: 'https://youtu.be/Whj85bHTRqU&t=5349',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '海の幽霊',
    songHira: 'うみのゆうれい',
    singer: '米津玄師',
    singerHira: 'よねづけんし',
    url: 'https://youtu.be/Whj85bHTRqU&t=5677',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'Darling',
    songHira: 'だーりん',
    singer: 'V6',
    singerHira: 'ぶいしっくす',
    url: 'https://youtu.be/Whj85bHTRqU&t=5878',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '初心LOVE',
    songHira: 'うぶらぶ',
    singer: 'なにわ男子',
    singerHira: 'なにわだんし',
    url: 'https://youtu.be/Whj85bHTRqU&t=6052',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: 'シンデレラガール',
    songHira: 'しんでれらがーる',
    singer: 'King&Prince',
    singerHira: 'きんぐあんどぷりんす',
    url: 'https://youtu.be/Whj85bHTRqU&t=6465',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
  {
    song: '君が代',
    songHira: 'きみがよ',
    singer: '国歌',
    singerHira: '',
    url: 'https://youtu.be/Whj85bHTRqU&t=6603',
    thumbnails: 'https://img.youtube.com/vi/Whj85bHTRqU/maxresdefault.jpg',
    title: 'ときめき！胸キュン！！バーチャルおばあちゃんのGW三味線弾き語りライブ',
    date: '2022/05/03',
  },
];

export default L;
